from django.urls import path

from . import (
    views,
    views_assinados,
    views_editor,
    views_ordens,
    views_planos,
    views_roteiros,
    views_termos,
)

app_name = "viagens"

urlpatterns = [
    path("", views.painel, name="painel"),
    path("oficios/", views.lista, name="oficios"),
    path("oficios/novo/", views.novo, name="novo"),
    path("oficios/exportar/", views.exportar, name="exportar_oficios"),
    path("oficios/numeracao/", views.numeracao, name="numeracao"),
    path("justificativas/", views.justificativas, name="justificativas"),
    path("justificativas/<int:pk>/salvar/", views.salvar_justificativa,
         name="salvar_justificativa"),
    path("oficios/<int:pk>/editar/", views.editar, name="editar"),
    path("oficios/<int:pk>/resumo/", views.resumo, name="resumo"),
    path("oficios/<int:pk>/equipe/adicionar/", views.adicionar_viajante,
         name="adicionar_viajante"),
    path("oficios/<int:pk>/equipe/<int:viajante_id>/remover/", views.remover_viajante,
         name="remover_viajante"),
    path("oficios/<int:pk>/equipe/motorista/", views.definir_motorista,
         name="definir_motorista"),
    path("oficios/<int:pk>/diarias/", views.secao_diarias, name="secao_diarias"),
    path("oficios/<int:pk>/emitir/confirmar/", views.emitir, name="emitir"),
    path("oficios/<int:pk>/autosave/", views.autosave, name="autosave_oficio"),
    path("oficios/<int:pk>/retificar/", views.retificar, name="retificar"),
    path("oficios/<int:pk>/reabrir/", views.reabrir, name="reabrir"),
    path("oficios/<int:pk>/cancelar/", views.cancelar, name="cancelar"),
    path("oficios/<int:pk>/reativar/", views.reativar, name="reativar"),
    path("oficios/<int:pk>/arquivar/", views.arquivar, name="arquivar"),
    path("oficios/<int:pk>/desarquivar/", views.desarquivar, name="desarquivar"),
    path("oficios/<int:pk>/excluir/", views.excluir, name="excluir"),
    path("oficios/<int:pk>/documentos/", views.documentos_parcial, name="documentos"),
    path("oficios/<int:pk>/minuta.pdf", views.previa, name="previa"),
    path("oficios/<int:pk>/documento/<str:tipo>.docx", views.baixar_docx, name="baixar_docx"),
    # Editor de documento no visualizador (ADR 0018)
    path("oficios/<int:pk>/documento/<str:tipo>/folha/", views_editor.folha, name="folha"),
    path("oficios/<int:pk>/documento/<str:tipo>/estado/", views_editor.estado,
         name="editor_estado"),
    path("oficios/<int:pk>/documento/<str:tipo>/salvar/", views_editor.salvar,
         name="editor_salvar"),
    path("oficios/<int:pk>/documento/<str:tipo>/restaurar/<int:numero>/",
         views_editor.restaurar, name="editor_restaurar"),
    path("oficios/<int:pk>/documento/<str:tipo>/modelo/", views_editor.modelo,
         name="editor_modelo"),
    path("oficios/<int:pk>/documento/<str:tipo>/campos/<str:chave>/", views_editor.campo,
         name="editor_campo"),
    path("oficios/<int:pk>/documento/<str:tipo>/original/", views_editor.original,
         name="editor_original"),
    path("oficios/<int:pk>/documento/<str:tipo>/paginas/", views_editor.paginas,
         name="editor_paginas"),
    path("oficios/<int:pk>/documento/<str:tipo>/presenca/", views_editor.presenca,
         name="editor_presenca"),
    path("oficios/<int:pk>/documento/<str:tipo>/textos/", views_editor.textos,
         name="editor_textos"),
    path("oficios/<int:pk>/documento/<str:tipo>/textos/<int:texto_id>/remover/",
         views_editor.remover_texto, name="editor_remover_texto"),
    path("documentos/<int:documento_id>/", views.baixar_documento, name="baixar_documento"),
    path("assinados/via/<int:via_pk>/", views_assinados.abrir, name="abrir_via_assinada"),
    path("assinados/via/<int:via_pk>/remover/", views_assinados.remover,
         name="remover_via_assinada"),
    path("assinados/<str:tipo>/<int:pk>/", views_assinados.anexar, name="anexar_assinado"),
    path("assinados/<str:tipo>/<int:pk>/<str:chave>/", views_assinados.anexar,
         name="anexar_assinado_de"),
    path("api/servidores/", views.buscar_servidores, name="buscar_servidores"),
    path("api/rota/", views.rota, name="rota"),
    path("termos/", views_termos.lista, name="termos"),
    path("termos/novo/", views_termos.novo, name="novo_termo"),
    path("termos/do-oficio/<int:oficio_pk>/", views_termos.criar_do_oficio,
         name="criar_termo_do_oficio"),
    path("termos/<int:pk>/", views_termos.editar, name="editar_termo"),
    path("termos/<int:pk>/documento/<str:chave>.<str:formato>", views_termos.documento,
         name="documento_termo"),
    path("termos/<int:pk>/todos.<str:formato>", views_termos.todos, name="todos_termo"),
    path("termos/<int:pk>/autosave/", views_termos.autosave, name="autosave_termo"),
    path("termos/<int:pk>/folha/<str:chave>/", views_termos.folha, name="folha_termo"),
    path("termos/<int:pk>/cancelar/", views_termos.cancelar, name="cancelar_termo"),
    path("termos/<int:pk>/reativar/", views_termos.reativar, name="reativar_termo"),
    path("termos/<int:pk>/excluir/", views_termos.excluir, name="excluir_termo"),
    path("api/oficios/", views_termos.buscar_oficios, name="buscar_oficios"),
    path("ordens/", views_ordens.lista, name="ordens"),
    path("ordens/nova/", views_ordens.nova, name="nova_ordem"),
    path("ordens/do-oficio/<int:oficio_pk>/", views_ordens.criar_do_oficio,
         name="criar_ordem_do_oficio"),
    path("ordens/<int:pk>/", views_ordens.editar, name="editar_ordem"),
    path("ordens/<int:pk>/autosave/", views_ordens.autosave, name="autosave_ordem"),
    path("ordens/<int:pk>/folha/", views_ordens.folha, name="folha_ordem"),
    path("ordens/<int:pk>/documento.<str:formato>", views_ordens.documento,
         name="documento_ordem"),
    path("ordens/<int:pk>/cancelar/", views_ordens.cancelar, name="cancelar_ordem"),
    path("ordens/<int:pk>/reativar/", views_ordens.reativar, name="reativar_ordem"),
    path("ordens/<int:pk>/excluir/", views_ordens.excluir, name="excluir_ordem"),
    path("planos/", views_planos.lista, name="planos"),
    path("planos/novo/", views_planos.novo, name="novo_plano"),
    path("planos/do-oficio/<int:oficio_pk>/", views_planos.criar_do_oficio,
         name="criar_plano_do_oficio"),
    path("planos/<int:pk>/", views_planos.editar, name="editar_plano"),
    path("planos/<int:pk>/autosave/", views_planos.autosave, name="autosave_plano"),
    path("planos/<int:pk>/finalizar/", views_planos.finalizar, name="finalizar_plano"),
    path("planos/<int:pk>/resultados/", views_planos.resultados_do_plano,
         name="resultados_plano"),
    path("planos/<int:pk>/eventos/salvar/", views_planos.salvar_evento,
         name="salvar_evento_plano"),
    path("planos/<int:pk>/eventos/<int:evento_pk>/remover/", views_planos.remover_evento,
         name="remover_evento_plano"),
    path("planos/<int:pk>/folha/", views_planos.folha, name="folha_plano"),
    path("planos/<int:pk>/documento.<str:formato>", views_planos.documento,
         name="documento_plano"),
    path("planos/<int:pk>/cancelar/", views_planos.cancelar, name="cancelar_plano"),
    path("planos/<int:pk>/reativar/", views_planos.reativar, name="reativar_plano"),
    path("planos/<int:pk>/excluir/", views_planos.excluir, name="excluir_plano"),
    path("roteiros/", views_roteiros.lista, name="roteiros"),
    path("roteiros/novo/", views_roteiros.novo, name="novo_roteiro"),
    path("roteiros/previa-diarias/", views_roteiros.previa_diarias,
         name="previa_diarias_roteiro"),
    path("roteiros/previa-trechos/", views_roteiros.previa_trechos,
         name="previa_trechos_roteiro"),
    path("roteiros/autosave/", views_roteiros.autosave, name="autosave_roteiro"),
    path("roteiros/<int:pk>/oficios/", views_roteiros.oficios_do_roteiro,
         name="oficios_do_roteiro"),
    path("roteiros/<int:pk>/editar/", views_roteiros.editar, name="editar_roteiro"),
    path("roteiros/<int:pk>/cancelar/", views_roteiros.cancelar, name="cancelar_roteiro"),
    path("roteiros/<int:pk>/reativar/", views_roteiros.reativar, name="reativar_roteiro"),
    path("roteiros/<int:pk>/excluir/", views_roteiros.excluir, name="excluir_roteiro"),
    path("roteiros/<int:pk>/criar-oficio/", views_roteiros.criar_oficio,
         name="criar_oficio_do_roteiro"),
]
