from django.urls import path

from . import views, views_editor, views_roteiros

app_name = "viagens"

urlpatterns = [
    path("", views.painel, name="painel"),
    path("oficios/", views.lista, name="oficios"),
    path("oficios/novo/", views.novo, name="novo"),
    path("oficios/exportar/", views.exportar, name="exportar_oficios"),
    path("oficios/numeracao/", views.numeracao, name="numeracao"),
    path("oficios/<int:pk>/editar/", views.editar, name="editar"),
    path("oficios/<int:pk>/resumo/", views.resumo, name="resumo"),
    path("oficios/<int:pk>/equipe/adicionar/", views.adicionar_viajante,
         name="adicionar_viajante"),
    path("oficios/<int:pk>/equipe/<int:viajante_id>/remover/", views.remover_viajante,
         name="remover_viajante"),
    path("oficios/<int:pk>/equipe/motorista/", views.definir_motorista,
         name="definir_motorista"),
    path("oficios/<int:pk>/diarias/", views.secao_diarias, name="secao_diarias"),
    path("oficios/<int:pk>/emitir/confirmar/", views.emitir, name="emitir"),
    path("oficios/<int:pk>/autosave/", views.autosave, name="autosave_oficio"),
    path("oficios/<int:pk>/retificar/", views.retificar, name="retificar"),
    path("oficios/<int:pk>/reabrir/", views.reabrir, name="reabrir"),
    path("oficios/<int:pk>/cancelar/", views.cancelar, name="cancelar"),
    path("oficios/<int:pk>/excluir/", views.excluir, name="excluir"),
    path("oficios/<int:pk>/documentos/", views.documentos_parcial, name="documentos"),
    path("oficios/<int:pk>/minuta.pdf", views.previa, name="previa"),
    # Editor de documento no visualizador (ADR 0018)
    path("oficios/<int:pk>/documento/<str:tipo>/folha/", views_editor.folha, name="folha"),
    path("oficios/<int:pk>/documento/<str:tipo>/estado/", views_editor.estado,
         name="editor_estado"),
    path("oficios/<int:pk>/documento/<str:tipo>/salvar/", views_editor.salvar,
         name="editor_salvar"),
    path("oficios/<int:pk>/documento/<str:tipo>/restaurar/<int:numero>/",
         views_editor.restaurar, name="editor_restaurar"),
    path("oficios/<int:pk>/documento/<str:tipo>/modelo/", views_editor.modelo,
         name="editor_modelo"),
    path("oficios/<int:pk>/documento/<str:tipo>/campos/<str:chave>/", views_editor.campo,
         name="editor_campo"),
    path("oficios/<int:pk>/documento/<str:tipo>/original/", views_editor.original,
         name="editor_original"),
    path("oficios/<int:pk>/documento/<str:tipo>/paginas/", views_editor.paginas,
         name="editor_paginas"),
    path("oficios/<int:pk>/documento/<str:tipo>/presenca/", views_editor.presenca,
         name="editor_presenca"),
    path("oficios/<int:pk>/documento/<str:tipo>/textos/", views_editor.textos,
         name="editor_textos"),
    path("oficios/<int:pk>/documento/<str:tipo>/textos/<int:texto_id>/remover/",
         views_editor.remover_texto, name="editor_remover_texto"),
    path("documentos/<int:documento_id>/", views.baixar_documento, name="baixar_documento"),
    path("api/servidores/", views.buscar_servidores, name="buscar_servidores"),
    path("api/rota/", views.rota, name="rota"),
    path("roteiros/", views_roteiros.lista, name="roteiros"),
    path("roteiros/novo/", views_roteiros.novo, name="novo_roteiro"),
    path("roteiros/previa-diarias/", views_roteiros.previa_diarias,
         name="previa_diarias_roteiro"),
    path("roteiros/previa-trechos/", views_roteiros.previa_trechos,
         name="previa_trechos_roteiro"),
    path("roteiros/autosave/", views_roteiros.autosave, name="autosave_roteiro"),
    path("roteiros/<int:pk>/oficios/", views_roteiros.oficios_do_roteiro,
         name="oficios_do_roteiro"),
    path("roteiros/<int:pk>/editar/", views_roteiros.editar, name="editar_roteiro"),
    path("roteiros/<int:pk>/cancelar/", views_roteiros.cancelar, name="cancelar_roteiro"),
    path("roteiros/<int:pk>/reativar/", views_roteiros.reativar, name="reativar_roteiro"),
    path("roteiros/<int:pk>/excluir/", views_roteiros.excluir, name="excluir_roteiro"),
    path("roteiros/<int:pk>/criar-oficio/", views_roteiros.criar_oficio,
         name="criar_oficio_do_roteiro"),
]
