# Generated by Django 6.1.1 on 2026-10-01 16:12

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Combustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=60, verbose_name="nome")),
            ],
            options={
                "verbose_name": "combustível",
                "verbose_name_plural": "combustíveis",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ModeloTexto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("motivo", "Motivo do ofício"),
                            ("justificativa", "Justificativa de prazo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                ("texto", models.TextField(verbose_name="texto")),
            ],
            options={
                "verbose_name": "modelo de texto",
                "verbose_name_plural": "modelos de texto",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
            ],
            options={
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nome"),
                        name="cargo_nome_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_ibge",
                    models.CharField(
                        max_length=7, unique=True, verbose_name="código IBGE"
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                ("uf", models.CharField(max_length=2, verbose_name="UF")),
            ],
            options={
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("nome"),
                        models.F("uf"),
                        name="municipio_nome_uf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TabelaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faixa",
                    models.CharField(
                        choices=[
                            ("interior", "Interior"),
                            ("capital", "Capital"),
                            ("brasilia", "Brasília"),
                        ],
                        max_length=10,
                        verbose_name="faixa",
                    ),
                ),
                ("vigente_desde", models.DateField(verbose_name="vigente a partir de")),
                (
                    "valor_24h",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="diária de 24 horas",
                    ),
                ),
                (
                    "norma",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="norma de referência"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "vigência de diária",
                "verbose_name_plural": "tabela de diárias",
                "ordering": ["faixa", "-vigente_desde"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("faixa", "vigente_desde"), name="diaria_vigencia_unica"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_24h__gt", 0)),
                        name="diaria_valor_positivo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("sigla", models.CharField(max_length=40, verbose_name="sigla")),
                ("nome", models.CharField(max_length=255, verbose_name="nome")),
            ],
            options={
                "ordering": ["sigla"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nome"),
                        name="unidade_nome_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Lotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotacoes",
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "lotação",
                "verbose_name_plural": "lotações",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_extenso",
                    models.CharField(
                        max_length=160, verbose_name="nome da unidade no cabeçalho"
                    ),
                ),
                (
                    "endereco_rodape",
                    models.CharField(max_length=255, verbose_name="endereço no rodapé"),
                ),
                (
                    "chefia_nome",
                    models.CharField(
                        max_length=150, verbose_name="nome da chefia (signatário)"
                    ),
                ),
                (
                    "chefia_cargo",
                    models.CharField(max_length=150, verbose_name="cargo da chefia"),
                ),
                (
                    "destinatario_tratamento",
                    models.CharField(
                        default="Exmo. Sr", max_length=40, verbose_name="tratamento"
                    ),
                ),
                (
                    "destinatario_nome",
                    models.CharField(max_length=150, verbose_name="destinatário"),
                ),
                (
                    "destinatario_cargo",
                    models.CharField(
                        max_length=150, verbose_name="cargo do destinatário"
                    ),
                ),
                (
                    "destinatario_orgao",
                    models.CharField(max_length=160, verbose_name="órgão de destino"),
                ),
                (
                    "destinatario_cidade",
                    models.CharField(
                        default="CURITIBA – Pr.",
                        max_length=80,
                        verbose_name="cidade do destinatário",
                    ),
                ),
                (
                    "prazo_justificativa_dias",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Viagens com menos dias de antecedência exigem justificativa.",
                        verbose_name="antecedência mínima (dias)",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.municipio",
                        verbose_name="cidade sede",
                    ),
                ),
                (
                    "unidade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracao",
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuração institucional",
                "verbose_name_plural": "configurações institucionais",
            },
        ),
        migrations.CreateModel(
            name="Servidor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=30, verbose_name="RG")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="telefone"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servidores",
                        to="cadastros.cargo",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servidores",
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "servidores",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("nome"),
                        name="servidor_nome_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cpf", ""), _negated=True),
                        fields=("cpf",),
                        name="servidor_cpf_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cpf", ""), ("cpf__regex", "^\\d{11}$"), _connector="OR"
                        ),
                        name="servidor_cpf_11_digitos",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Viatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "placa",
                    models.CharField(max_length=7, unique=True, verbose_name="placa"),
                ),
                ("modelo", models.CharField(max_length=120, verbose_name="modelo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("caracterizada", "Caracterizada"),
                            ("descaracterizada", "Descaracterizada"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "combustivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.combustivel",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viaturas",
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["placa"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("placa__regex", "^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$")
                        ),
                        name="viatura_placa_formato",
                    )
                ],
            },
        ),
    ]
