# Generated by Django 6.1.1 on 2026-10-02 03:41

from django.db import migrations, models


def preencher(apps, schema_editor):
    from gestao.cadastros.carga import preencher_coordenadas

    preencher_coordenadas(apps.get_model("cadastros", "Municipio"))


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_auditoria_municipios"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipio",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.RunPython(preencher, migrations.RunPython.noop),
    ]
