# Generated by Django 6.1.1 on 2026-10-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_coordenadas_municipios"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelotexto",
            name="padrao_sistema",
            field=models.BooleanField(default=False, verbose_name="padrão do sistema"),
        ),
        migrations.AlterField(
            model_name="modelotexto",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("motivo", "Motivo do ofício"),
                    ("justificativa", "Justificativa de prazo"),
                    ("oficio", "Trecho para o texto do ofício"),
                ],
                max_length=20,
            ),
        ),
    ]
