# Generated by Django 6.1.1 on 2026-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_editor_de_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="viatura",
            name="motoristas",
            field=models.ManyToManyField(
                blank=True,
                related_name="viaturas_que_dirige",
                to="cadastros.servidor",
                verbose_name="motoristas habituais",
            ),
        ),
    ]
