# Generated by Django 6.1.1 on 2026-10-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_viatura_motoristas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelotexto',
            options={'ordering': ['tipo', 'ordem', 'nome'], 'verbose_name': 'modelo de texto', 'verbose_name_plural': 'modelos de texto'},
        ),
        migrations.AddField(
            model_name='modelotexto',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='ordem'),
        ),
        migrations.AddField(
            model_name='modelotexto',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='padrão'),
        ),
        migrations.AddConstraint(
            model_name='modelotexto',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('tipo',), name='modelotexto_um_padrao_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='modelotexto',
            constraint=models.CheckConstraint(condition=models.Q(('ativo', False), ('padrao', True), _negated=True), name='modelotexto_padrao_ativo'),
        ),
    ]
