# Generated by Django 6.1.1 on 2026-10-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_modelo_texto_ordem_e_padrao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelotexto',
            options={'ordering': ['tipo', 'ordem', 'nome'], 'permissions': [('gerir_padrao_texto', 'Definir o texto padrão e alterar textos padrão ou do sistema')], 'verbose_name': 'modelo de texto', 'verbose_name_plural': 'modelos de texto'},
        ),
    ]
