# Generated by Django 6.1.1 on 2026-10-03 23:11

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models
from django.db.models.functions import Lower

from gestao.cadastros.validacoes import normalizar_rg, somente_digitos


def normalizar_documentos(apps, schema_editor):
    """RG e telefone passam a ser guardados normalizados (como o formulário grava), e só
    então nome, RG e telefone viram únicos. Duplicado não é resolvido em silêncio: a
    migração para e diz quais registros conferir."""
    Servidor = apps.get_model("cadastros", "Servidor")
    Combustivel = apps.get_model("cadastros", "Combustivel")
    for s in Servidor.objects.all():
        rg, telefone = normalizar_rg(s.rg), somente_digitos(s.telefone)
        if (rg, telefone) != (s.rg, s.telefone):
            Servidor.objects.filter(pk=s.pk).update(rg=rg, telefone=telefone)
    problemas = []
    for modelo, rotulo, campo, excluir in (
            (Servidor, "servidores com o mesmo nome", Lower("nome"), {}),
            (Servidor, "servidores com o mesmo RG", models.F("rg"), {"rg__in": ["", "NÃO POSSUI RG"]}),
            (Servidor, "servidores com o mesmo telefone", models.F("telefone"), {"telefone": ""}),
            (Combustivel, "combustíveis com o mesmo nome", Lower("nome"), {})):
        repetidos = (modelo.objects.exclude(**excluir).annotate(chave=campo).values("chave")
                     .annotate(n=models.Count("id")).filter(n__gt=1))
        problemas += [f"{rotulo}: {r['chave']!r} ({r['n']})" for r in repetidos]
    if problemas:
        raise RuntimeError("Cadastros duplicados impedem as novas regras de unicidade; "
                           "corrija antes de migrar: " + "; ".join(problemas))


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_permissao_padrao_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='padrão'),
        ),
        migrations.AddField(
            model_name='combustivel',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='padrão'),
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='cadastros.cargo'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidores', to='cadastros.unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='combustivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='cadastros.combustivel'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='modelo',
            field=models.CharField(blank=True, max_length=120, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='tipo',
            field=models.CharField(blank=True, choices=[('caracterizada', 'Caracterizada'), ('descaracterizada', 'Descaracterizada')], max_length=20, verbose_name='tipo'),
        ),
        migrations.RunPython(normalizar_documentos, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('padrao',), name='cargo_um_padrao'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.CheckConstraint(condition=models.Q(('ativo', False), ('padrao', True), _negated=True), name='cargo_padrao_ativo'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='combustivel_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('padrao',), name='combustivel_um_padrao'),
        ),
        migrations.AddConstraint(
            model_name='combustivel',
            constraint=models.CheckConstraint(condition=models.Q(('ativo', False), ('padrao', True), _negated=True), name='combustivel_padrao_ativo'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='servidor_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('rg', ''), _negated=True), models.Q(('rg', 'NÃO POSSUI RG'), _negated=True)), fields=('rg',), name='servidor_rg_unico'),
        ),
        migrations.AddConstraint(
            model_name='servidor',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone', ''), _negated=True), fields=('telefone',), name='servidor_telefone_unico'),
        ),
    ]
