# Generated by Django 6.1.1 on 2026-10-04 01:02

import django.db.models.deletion
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_cadastro_incompleto_e_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='assina_justificativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='assina as justificativas'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='assina_oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='assina os ofícios'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='bairro',
            field=models.CharField(blank=True, max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='cep',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='cidade_endereco',
            field=models.CharField(blank=True, max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='logradouro',
            field=models.CharField(blank=True, max_length=160, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='ramal',
            field=models.CharField(blank=True, max_length=20, verbose_name='ramal'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='configuracaoinstitucional',
            name='endereco_rodape',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço no rodapé'),
        ),
        migrations.CreateModel(
            name='SubstituicaoAssinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('todos', 'Todos os documentos'), ('oficio', 'Ofício'), ('justificativa', 'Justificativa')], default='todos', max_length=20, verbose_name='documentos')),
                ('inicio', models.DateField(verbose_name='início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='cadastros.configuracaoinstitucional')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.servidor', verbose_name='substituto')),
            ],
            options={
                'verbose_name': 'substituição de assinante',
                'verbose_name_plural': 'substituições de assinante',
                'ordering': ['-inicio', 'tipo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__isnull', True), ('fim__gte', models.F('inicio')), _connector='OR'), name='substituicao_periodo_ordenado')],
            },
        ),
        auditar_tabela("cadastros_substituicaoassinante"),
    ]
