# Generated by Django 6.1.1 on 2026-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_assinantes_e_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='delegado_geral_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Delegado-Geral'),
        ),
    ]
