# Generated by Django 6.1.1 on 2026-10-04 05:44

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_delegado_geral'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=255, verbose_name='atividade')),
                ('meta', models.TextField(verbose_name='meta')),
                ('recurso', models.TextField(blank=True, verbose_name='recursos necessários')),
            ],
            options={
                'verbose_name': 'atividade do plano',
                'verbose_name_plural': 'atividades do plano',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='assina_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='assina os planos de trabalho'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='coordenador_plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='coordenador administrativo padrão'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='sufixo_plano',
            field=models.CharField(blank=True, max_length=20, verbose_name='sufixo da numeração do plano'),
        ),
        migrations.AlterField(
            model_name='substituicaoassinante',
            name='tipo',
            field=models.CharField(choices=[('todos', 'Todos os documentos'), ('oficio', 'Ofício'), ('justificativa', 'Justificativa'), ('plano_trabalho', 'Plano de trabalho')], default='todos', max_length=20, verbose_name='documentos'),
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=60, verbose_name='faixa')),
            ],
            options={
                'verbose_name': 'horário de atendimento',
                'verbose_name_plural': 'horários de atendimento',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='horario_nome_unico')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'programa solicitante',
                'verbose_name_plural': 'programas solicitantes',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='programa_nome_unico')],
            },
        ),
        migrations.CreateModel(
            name='PresetAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('padrao', models.BooleanField(default=False, verbose_name='padrão')),
                ('atividades', models.ManyToManyField(related_name='presets', to='cadastros.atividadeplano', verbose_name='atividades')),
            ],
            options={
                'verbose_name': 'conjunto de atividades',
                'verbose_name_plural': 'conjuntos de atividades',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='preset_nome_unico'), models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('padrao',), name='preset_um_padrao'), models.CheckConstraint(condition=models.Q(('ativo', False), ('padrao', True), _negated=True), name='preset_padrao_ativo')],
            },
        ),
    ]
