# Generated by Django 6.1.1 on 2026-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_catalogos_do_plano_auditoria_e_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='coordenador_plano_genero',
            field=models.CharField(blank=True, max_length=1, verbose_name='como sai no documento'),
        ),
    ]
