# Generated by Django 6.1.1 on 2026-10-04 18:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_coordenador_plano_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'tipo de viagem',
                'verbose_name_plural': 'tipos de viagem',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='tipo_viagem_nome_unico')],
            },
        ),
    ]
