# Generated by Django 6.1.1 on 2026-10-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_tipos_de_viagem_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelotexto',
            name='tipo',
            field=models.CharField(choices=[('motivo', 'Motivo do ofício'), ('justificativa', 'Justificativa de prazo'), ('oficio', 'Trecho para o texto do ofício'), ('rt_motivo', 'RT · Descrição do evento'), ('rt_atividade', 'RT · Objetivo da participação'), ('rt_conclusao', 'RT · Conclusão'), ('rt_medidas', 'RT · Medidas a serem adotadas'), ('rt_info', 'RT · Informações complementares')], max_length=20),
        ),
    ]
