# Generated by Django 6.1.1 on 2026-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_notificacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaDoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(unique=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'rotina do dia',
                'verbose_name_plural': 'rotinas do dia',
            },
        ),
    ]
