# Generated by Django 6.1.1 on 2026-10-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_rotina_do_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('selo', models.CharField(max_length=32)),
                ('gerada_em', models.DateTimeField()),
                ('usada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assinatura da agenda',
                'verbose_name_plural': 'assinaturas da agenda',
            },
        ),
    ]
