# Generated by Django 6.1.1 on 2026-10-01 16:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0002_auditoria_municipios"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeracaoAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(unique=True)),
                ("piso", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "numeração anual",
                "verbose_name_plural": "numeração anual",
            },
        ),
        migrations.CreateModel(
            name="Oficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField(verbose_name="ano")),
                ("numero", models.PositiveIntegerField(verbose_name="número")),
                ("data_oficio", models.DateField(verbose_name="data do ofício")),
                (
                    "protocolo",
                    models.CharField(
                        blank=True,
                        help_text="Nove dígitos, com ou sem pontuação (ex.: 26.655.434-6).",
                        max_length=9,
                        verbose_name="protocolo (eProtocolo)",
                    ),
                ),
                (
                    "assunto",
                    models.CharField(
                        default="Solicitação de autorização e concessão de diárias",
                        max_length=200,
                        verbose_name="assunto",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(blank=True, verbose_name="motivo da viagem"),
                ),
                (
                    "custeio",
                    models.CharField(
                        choices=[
                            (
                                "unidade",
                                "Unidade (diárias e combustível custeados pela unidade)",
                            ),
                            ("outra_instituicao", "Outra instituição"),
                            (
                                "onus_limitado",
                                "Ônus limitados aos próprios vencimentos",
                            ),
                        ],
                        default="unidade",
                        max_length=20,
                        verbose_name="custeio",
                    ),
                ),
                (
                    "custeio_instituicao",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="instituição que custeia",
                    ),
                ),
                (
                    "tipo_transporte",
                    models.CharField(
                        choices=[
                            ("viatura", "Viatura oficial"),
                            ("outro", "Outro meio (informar)"),
                        ],
                        default="viatura",
                        max_length=10,
                        verbose_name="meio de transporte",
                    ),
                ),
                (
                    "transporte_descricao",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="descrição do transporte",
                    ),
                ),
                (
                    "transporte_placa",
                    models.CharField(blank=True, max_length=7, verbose_name="placa"),
                ),
                (
                    "porte_arma",
                    models.BooleanField(
                        default=True, verbose_name="porte/trânsito de arma"
                    ),
                ),
                (
                    "justificativa",
                    models.TextField(blank=True, verbose_name="justificativa"),
                ),
                (
                    "diarias_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("diarias_resumo", models.CharField(blank=True, max_length=120)),
                ("diarias_calculo", models.JSONField(blank=True, default=dict)),
                ("diarias_erro", models.CharField(blank=True, max_length=300)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("emitido", "Emitido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=10,
                    ),
                ),
                ("versao", models.PositiveIntegerField(default=1)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("emitido_em", models.DateTimeField(blank=True, null=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_cancelamento", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "justificativa_modelo",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"tipo": "justificativa"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cadastros.modelotexto",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                        verbose_name="cidade sede",
                    ),
                ),
                (
                    "transporte_combustivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.combustivel",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oficios",
                        to="cadastros.unidade",
                        verbose_name="unidade emissora",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="oficios",
                        to="cadastros.viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "ofício",
                "verbose_name_plural": "ofícios",
                "ordering": ["-ano", "-numero"],
                "permissions": [
                    ("emitir_oficio", "Pode emitir ofícios"),
                    ("cancelar_oficio", "Pode cancelar ofícios"),
                    ("reabrir_oficio", "Pode reabrir ofícios emitidos"),
                    ("ver_todas_unidades", "Vê ofícios de todas as unidades"),
                    ("gerir_numeracao", "Pode configurar a numeração anual"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criado", "Rascunho criado"),
                            ("alterado", "Dados alterados"),
                            ("viajante", "Equipe alterada"),
                            ("emitido", "Ofício emitido"),
                            ("documento", "Documento gerado"),
                            ("reaberto", "Reaberto para correção"),
                            ("cancelado", "Ofício cancelado"),
                        ],
                        max_length=12,
                    ),
                ),
                ("descricao", models.CharField(max_length=300)),
                ("em", models.DateTimeField(auto_now_add=True)),
                ("dados", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="viagens.oficio",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico",
                "ordering": ["-em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("oficio", "Ofício"),
                            ("justificativa", "Justificativa"),
                        ],
                        max_length=15,
                    ),
                ),
                ("versao", models.PositiveSmallIntegerField()),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("gerando", "Gerando"),
                            ("pronto", "Pronto"),
                            ("falhou", "Falhou"),
                        ],
                        default="gerando",
                        max_length=10,
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        default=dict, verbose_name="instantâneo dos dados usados"
                    ),
                ),
                ("arquivo", models.FileField(blank=True, upload_to="documentos/%Y/")),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                ("erro", models.TextField(blank=True)),
                ("emitido_em", models.DateTimeField(auto_now_add=True)),
                ("gerado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "emitido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="viagens.oficio",
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "-versao"],
            },
        ),
        migrations.CreateModel(
            name="Trecho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField()),
                ("saida_em", models.DateTimeField(verbose_name="saída")),
                ("chegada_em", models.DateTimeField(verbose_name="chegada")),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trechos",
                        to="viagens.oficio",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Viajante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motorista",
                    models.BooleanField(default=False, verbose_name="motorista"),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajantes",
                        to="viagens.oficio",
                    ),
                ),
                (
                    "servidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viagens",
                        to="cadastros.servidor",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="oficio",
            index=models.Index(
                fields=["situacao", "-ano", "-numero"], name="oficio_situacao_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oficio",
            index=models.Index(
                fields=["unidade", "-ano", "-numero"], name="oficio_unidade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oficio",
            index=models.Index(fields=["protocolo"], name="oficio_protocolo_idx"),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.UniqueConstraint(
                fields=("ano", "numero"), name="oficio_numero_unico_ano"
            ),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero__gt", 0)), name="oficio_numero_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.CheckConstraint(
                condition=models.Q(("diarias_total__gte", 0)),
                name="oficio_diarias_nao_negativas",
            ),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("protocolo", ""), ("protocolo__regex", "^\\d{9}$"), _connector="OR"
                ),
                name="oficio_protocolo_9_digitos",
            ),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("situacao", "emitido"), _negated=True),
                    ("emitido_em__isnull", False),
                    _connector="OR",
                ),
                name="oficio_emitido_tem_data",
            ),
        ),
        migrations.AddConstraint(
            model_name="oficio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("situacao", "cancelado"), _negated=True),
                    models.Q(("motivo_cancelamento", ""), _negated=True),
                    _connector="OR",
                ),
                name="oficio_cancelado_tem_motivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="documento",
            constraint=models.UniqueConstraint(
                fields=("oficio", "tipo", "versao"), name="documento_versao_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="documento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("situacao", "pronto"), _negated=True),
                    models.Q(("sha256", ""), _negated=True),
                    _connector="OR",
                ),
                name="documento_pronto_tem_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="trecho",
            constraint=models.UniqueConstraint(
                fields=("oficio", "ordem"), name="trecho_ordem_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="trecho",
            constraint=models.CheckConstraint(
                condition=models.Q(("chegada_em__gt", models.F("saida_em"))),
                name="trecho_chega_depois_de_sair",
            ),
        ),
        migrations.AddConstraint(
            model_name="trecho",
            constraint=models.CheckConstraint(
                condition=models.Q(("origem", models.F("destino")), _negated=True),
                name="trecho_origem_diferente_destino",
            ),
        ),
        migrations.AddConstraint(
            model_name="viajante",
            constraint=models.UniqueConstraint(
                fields=("oficio", "servidor"), name="viajante_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="viajante",
            constraint=models.UniqueConstraint(
                condition=models.Q(("motorista", True)),
                fields=("oficio",),
                name="um_motorista_por_oficio",
            ),
        ),
    ]
