# Generated by Django 6.1.1 on 2026-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0002_auditoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oficio",
            name="assunto",
        ),
        migrations.AddField(
            model_name="oficio",
            name="marcador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nenhum (documento original)"),
                    ("retificado", "Retificado (corrige ofício anterior à viagem)"),
                    ("complementar", "Complementar (acrescenta ao ofício já enviado)"),
                ],
                default="",
                max_length=15,
                verbose_name="marcador do documento",
            ),
        ),
    ]
