# Generated by Django 6.1.1 on 2026-10-01 18:08

from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0003_assunto_calculado_marcador"),
    ]

    operations = [
        migrations.CreateModel(
            name="LacunaNumeracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveSmallIntegerField()),
                ("numero", models.PositiveIntegerField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "lacuna de numeração",
                "verbose_name_plural": "lacunas de numeração",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ano", "numero"), name="lacuna_numeracao_unica"
                    )
                ],
            },
        ),
        auditar_tabela("viagens_lacunanumeracao"),
    ]
