# Generated by Django 6.1.1 on 2026-10-02 03:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_auditoria_municipios"),
        ("viagens", "0004_lacuna_numeracao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_servidores",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Efetivo usado para estimar as diárias do roteiro.",
                        verbose_name="quantidade de servidores",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("cancelado", "Cancelado")],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "diarias_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("diarias_resumo", models.CharField(blank=True, max_length=120)),
                ("diarias_calculo", models.JSONField(blank=True, default=dict)),
                ("diarias_erro", models.CharField(blank=True, max_length=300)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                        verbose_name="sede (origem da viagem)",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roteiros",
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "roteiro",
                "verbose_name_plural": "roteiros",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="oficio",
            name="roteiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oficios",
                to="viagens.roteiro",
                verbose_name="roteiro de origem",
            ),
        ),
        migrations.CreateModel(
            name="TrechoRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField()),
                ("saida_em", models.DateTimeField(verbose_name="saída")),
                ("chegada_em", models.DateTimeField(verbose_name="chegada")),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trechos",
                        to="viagens.roteiro",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.AddIndex(
            model_name="roteiro",
            index=models.Index(
                fields=["unidade", "situacao"], name="roteiro_unidade_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_servidores__gte", 1)),
                name="roteiro_ao_menos_um_servidor",
            ),
        ),
        migrations.AddConstraint(
            model_name="roteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("diarias_total__gte", 0)),
                name="roteiro_diarias_nao_negativas",
            ),
        ),
        migrations.AddConstraint(
            model_name="trechoroteiro",
            constraint=models.UniqueConstraint(
                fields=("roteiro", "ordem"), name="trecho_roteiro_ordem_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="trechoroteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("chegada_em__gt", models.F("saida_em"))),
                name="trecho_roteiro_chega_depois_de_sair",
            ),
        ),
        migrations.AddConstraint(
            model_name="trechoroteiro",
            constraint=models.CheckConstraint(
                condition=models.Q(("origem", models.F("destino")), _negated=True),
                name="trecho_roteiro_origem_diferente_destino",
            ),
        ),
        auditar_tabela("viagens_roteiro"),
        auditar_tabela("viagens_trechoroteiro"),
    ]
