# Generated by Django 6.1.1 on 2026-10-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_coordenadas_municipios"),
        ("viagens", "0005_roteiros"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanciaMunicipios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("km", models.DecimalField(decimal_places=1, max_digits=8)),
                (
                    "minutos",
                    models.PositiveIntegerField(verbose_name="tempo de estrada (min)"),
                ),
                ("geometria", models.JSONField(blank=True, default=list)),
                ("fonte", models.CharField(max_length=20)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="cadastros.municipio",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origem", "destino"), name="distancia_par_unico"
                    )
                ],
            },
        ),
    ]
