# Generated by Django 6.1.1 on 2026-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0006_distancias"),
    ]

    operations = [
        migrations.AddField(
            model_name="trecho",
            name="distancia_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="distância (km)",
            ),
        ),
        migrations.AddField(
            model_name="trecho",
            name="tempo_adicional_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="tempo adicional (min)"
            ),
        ),
        migrations.AddField(
            model_name="trecho",
            name="tempo_viagem_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="tempo de estrada (min)"
            ),
        ),
        migrations.AddField(
            model_name="trechoroteiro",
            name="distancia_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=8,
                null=True,
                verbose_name="distância (km)",
            ),
        ),
        migrations.AddField(
            model_name="trechoroteiro",
            name="tempo_adicional_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="tempo adicional (min)"
            ),
        ),
        migrations.AddField(
            model_name="trechoroteiro",
            name="tempo_viagem_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="tempo de estrada (min)"
            ),
        ),
    ]
