# Generated by Django 6.1.1 on 2026-10-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_coordenadas_municipios'),
        ('viagens', '0007_itinerario_tempos'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='bate_volta',
            field=models.BooleanField(default=False, verbose_name='bate-volta'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='bate_volta',
            field=models.BooleanField(default=False, verbose_name='bate-volta'),
        ),
        migrations.CreateModel(
            name='BateVolta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('dia_inicial', models.DateField(verbose_name='primeiro dia')),
                ('dia_final', models.DateField(verbose_name='último dia')),
                ('hora_saida', models.TimeField(verbose_name='hora de saída')),
                ('hora_volta', models.TimeField(verbose_name='hora da volta')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bate_voltas', to='viagens.oficio')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('oficio', 'ordem'), name='bate_volta_ordem_unica'), models.CheckConstraint(condition=models.Q(('dia_final__gte', models.F('dia_inicial'))), name='bate_volta_periodo_valido'), models.CheckConstraint(condition=models.Q(('hora_volta__gt', models.F('hora_saida'))), name='bate_volta_volta_no_mesmo_dia')],
            },
        ),
        migrations.CreateModel(
            name='BateVoltaRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('dia_inicial', models.DateField(verbose_name='primeiro dia')),
                ('dia_final', models.DateField(verbose_name='último dia')),
                ('hora_saida', models.TimeField(verbose_name='hora de saída')),
                ('hora_volta', models.TimeField(verbose_name='hora da volta')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bate_voltas', to='viagens.roteiro')),
            ],
            options={
                'ordering': ['ordem'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('roteiro', 'ordem'), name='bate_volta_roteiro_ordem_unica'), models.CheckConstraint(condition=models.Q(('dia_final__gte', models.F('dia_inicial'))), name='bate_volta_roteiro_periodo_valido'), models.CheckConstraint(condition=models.Q(('hora_volta__gt', models.F('hora_saida'))), name='bate_volta_roteiro_volta_no_mesmo_dia')],
            },
        ),
    ]
