# Generated by Django 6.1.1 on 2026-10-03 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ("viagens", "0008_bate_volta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="acao",
            field=models.CharField(
                choices=[
                    ("criado", "Rascunho criado"),
                    ("alterado", "Dados alterados"),
                    ("viajante", "Equipe alterada"),
                    ("emitido", "Ofício emitido"),
                    ("documento", "Documento gerado"),
                    ("reaberto", "Reaberto para correção"),
                    ("cancelado", "Ofício cancelado"),
                    ("texto", "Texto do documento alterado"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="EdicaoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("oficio", "Ofício"),
                            ("justificativa", "Justificativa"),
                        ],
                        max_length=15,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("editado", "Texto editado"),
                            ("restaurado", "Versão restaurada"),
                            ("modelo", "Voltou ao modelo"),
                        ],
                        default="editado",
                        max_length=10,
                    ),
                ),
                (
                    "regioes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="HTML por região"
                    ),
                ),
                ("blocos_alterados", models.JSONField(blank=True, default=list)),
                ("impressoes", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oficio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edicoes",
                        to="viagens.oficio",
                    ),
                ),
                (
                    "restaurada_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="viagens.edicaodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "edição de documento",
                "verbose_name_plural": "edições de documento",
                "ordering": ["tipo", "-numero"],
            },
        ),
        migrations.AddField(
            model_name="documento",
            name="edicao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos",
                to="viagens.edicaodocumento",
            ),
        ),
        migrations.AddConstraint(
            model_name="edicaodocumento",
            constraint=models.UniqueConstraint(
                fields=("oficio", "tipo", "numero"),
                name="edicao_documento_numero_unico",
            ),
        ),
        auditar_tabela("viagens_edicaodocumento"),
    ]
