# Generated by Django 6.1.1 on 2026-10-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0009_editor_de_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='protocolo_origem',
            field=models.CharField(blank=True, choices=[('manual', 'Digitado'), ('eprotocolo', 'Aberto no eProtocolo'), ('treinamento', 'eProtocolo de treinamento (não oficial)'), ('simulado', 'Simulado (não oficial)')], max_length=12, verbose_name='origem do protocolo'),
        ),
    ]
