# Generated by Django 6.1.1 on 2026-10-03 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_situacao_anterior(apps, schema_editor):
    """Cancelados de antes desta migração: a situação anterior sai do histórico — a última
    transição antes do cancelamento (emitido → emitido; criado/reaberto → rascunho)."""
    Oficio = apps.get_model("viagens", "Oficio")
    Historico = apps.get_model("viagens", "Historico")
    for oficio in Oficio.objects.filter(situacao="cancelado", situacao_anterior=""):
        ultima = (Historico.objects.filter(oficio=oficio, acao__in=["emitido", "reaberto", "criado"])
                  .exclude(em__gt=oficio.cancelado_em or oficio.atualizado_em)
                  .order_by("-em", "-pk").values_list("acao", flat=True).first())
        anterior = "emitido" if ultima == "emitido" else "rascunho"
        Oficio.objects.filter(pk=oficio.pk).update(situacao_anterior=anterior)


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0010_origem_do_protocolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficio',
            options={'ordering': ['-ano', '-numero'], 'permissions': [('emitir_oficio', 'Pode emitir ofícios'), ('cancelar_oficio', 'Pode cancelar ofícios'), ('reabrir_oficio', 'Pode reabrir ofícios emitidos'), ('reativar_oficio', 'Pode reativar ofícios cancelados (com justificativa)'), ('arquivar_oficio', 'Pode arquivar e desarquivar ofícios'), ('ver_todas_unidades', 'Vê ofícios de todas as unidades'), ('gerir_numeracao', 'Pode configurar a numeração anual')], 'verbose_name': 'ofício', 'verbose_name_plural': 'ofícios'},
        ),
        migrations.AddField(
            model_name='oficio',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='arquivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oficio',
            name='situacao_anterior',
            field=models.CharField(blank=True, max_length=10, verbose_name='situação antes do cancelamento'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(choices=[('criado', 'Rascunho criado'), ('alterado', 'Dados alterados'), ('viajante', 'Equipe alterada'), ('emitido', 'Ofício emitido'), ('documento', 'Documento gerado'), ('reaberto', 'Reaberto para correção'), ('cancelado', 'Ofício cancelado'), ('reativado', 'Ofício reativado'), ('arquivado', 'Ofício arquivado'), ('desarquivado', 'Ofício desarquivado'), ('texto', 'Texto do documento alterado')], max_length=12),
        ),
        migrations.RunPython(preencher_situacao_anterior, migrations.RunPython.noop),
    ]
