# Generated by Django 6.1.1 on 2026-10-03 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_permissao_padrao_texto'),
        ('viagens', '0011_arquivar_e_reativar'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo',
            field=models.CharField(blank=True, choices=[('', 'Da equipe'), ('servidor', 'Servidor cadastrado (de outro ofício)'), ('manual', 'Pessoa não cadastrada')], max_length=10, verbose_name='motorista de fora da equipe'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_cargo',
            field=models.CharField(blank=True, max_length=120, verbose_name='cargo do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_observacao',
            field=models.TextField(blank=True, verbose_name='observação sobre o motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.servidor', verbose_name='servidor motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_externo_unidade',
            field=models.CharField(blank=True, max_length=255, verbose_name='unidade do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_origem',
            field=models.CharField(blank=True, max_length=12, verbose_name='ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_protocolo_origem',
            field=models.CharField(blank=True, max_length=9, verbose_name='protocolo do motorista'),
        ),
    ]
