# Generated by Django 6.1.1 on 2026-10-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0012_motorista_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='motorista_externo',
            field=models.CharField(blank=True, choices=[('', 'Da equipe'), ('servidor', 'Servidor de outro ofício'), ('manual', 'Pessoa não cadastrada')], max_length=10, verbose_name='motorista de fora da equipe'),
        ),
    ]
