# Generated by Django 6.1.1 on 2026-10-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0013_rotulo_motorista_externo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajante',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'participação em ofício', 'verbose_name_plural': 'participações em ofícios'},
        ),
    ]
