# Generated by Django 6.1.1 on 2026-10-04 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_assinantes_e_endereco'),
        ('viagens', '0014_rotulo_participacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(default='PCPR na Comunidade', max_length=160, verbose_name='evento')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=10)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=1000, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='viagens.oficio', verbose_name='ofício vinculado')),
                ('servidores', models.ManyToManyField(blank=True, related_name='termos', to='cadastros.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='cadastros.unidade')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='cadastros.viatura')),
            ],
            options={
                'verbose_name': 'termo de autorização',
                'verbose_name_plural': 'termos de autorização',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TermoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.termoautorizacao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='termoautorizacao',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', False)), _connector='OR'), name='termo_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='termoautorizacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('situacao', 'cancelado'), _negated=True), models.Q(('motivo_cancelamento', ''), _negated=True), _connector='OR'), name='termo_cancelado_tem_motivo'),
        ),
        migrations.AddConstraint(
            model_name='termodestino',
            constraint=models.UniqueConstraint(fields=('termo', 'municipio'), name='termo_destino_unico'),
        ),
        auditar_tabela("viagens_termoautorizacao"),
        auditar_tabela("viagens_termodestino"),
        auditar_tabela("viagens_termoautorizacao_servidores"),
    ]
