# Generated by Django 6.1.1 on 2026-10-04 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_delegado_geral'),
        ('viagens', '0015_termos_de_autorizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracaoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LacunaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'numero'), name='os_lacuna_unica')],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('padrao', 'Padrão / texto livre'), ('operacao_retorno_posterior', 'Operação policial - um dia posterior'), ('caminhao', 'Caminhão - dois dias antes e depois'), ('microonibus', 'Micro-ônibus'), ('cerimonial_antecipado', 'Cerimonial - ida antecipada')], default='padrao', max_length=40, verbose_name='tipo de necessidade')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('documento_gerado_em', models.DateTimeField(blank=True, null=True)),
                ('funcoes', models.JSONField(blank=True, default=dict, verbose_name='funções da equipe')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=10)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=1000)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='assinante desta OS')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficios', models.ManyToManyField(blank=True, related_name='ordens', to='viagens.oficio')),
                ('servidores', models.ManyToManyField(blank=True, related_name='ordens', to='cadastros.servidor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='cadastros.unidade')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ['-ano', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.ordemservico')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.UniqueConstraint(fields=('ano', 'numero'), name='os_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='os_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', False)), _connector='OR'), name='os_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='ordemservico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('situacao', 'cancelada'), _negated=True), models.Q(('motivo_cancelamento', ''), _negated=True), _connector='OR'), name='os_cancelada_tem_motivo'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicodestino',
            constraint=models.UniqueConstraint(fields=('ordem', 'municipio'), name='os_destino_unico'),
        ),
        auditar_tabela("viagens_ordemservico"),
        auditar_tabela("viagens_ordemservicodestino"),
        auditar_tabela("viagens_lacunaordemservico"),
        auditar_tabela("viagens_ordemservico_oficios"),
        auditar_tabela("viagens_ordemservico_servidores"),
        auditar_tabela("viagens_numeracaoordemservico"),
    ]
