# Generated by Django 6.1.1 on 2026-10-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_catalogos_do_plano_auditoria_e_carga'),
        ('viagens', '0016_ordens_de_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeracaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LacunaPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ano', 'numero'), name='plano_lacuna_unica')],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('sufixo', models.CharField(blank=True, max_length=20, verbose_name='sufixo do número')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerado', 'Gerado')], default='rascunho', max_length=10)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=1000, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('data_documento', models.DateField(blank=True, null=True, verbose_name='data do documento')),
                ('documento_gerado_em', models.DateTimeField(blank=True, null=True)),
                ('programa_outros', models.CharField(blank=True, max_length=200, verbose_name='outro programa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('horario', models.CharField(blank=True, default='09:00 até 17:00', max_length=60, verbose_name='horário de atendimento')),
                ('coordenador_adm_nome', models.CharField(blank=True, max_length=255, verbose_name='nome (fora do cadastro)')),
                ('coordenador_adm_cargo', models.CharField(blank=True, max_length=120, verbose_name='cargo (fora do cadastro)')),
                ('coordenador_adm_genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('coordenador_op_nome', models.CharField(blank=True, max_length=255, verbose_name='nome (fora do cadastro)')),
                ('coordenador_op_cargo', models.CharField(blank=True, max_length=120, verbose_name='cargo (fora do cadastro)')),
                ('coordenador_op_genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('contextualizacao', models.TextField(blank=True)),
                ('contextualizacao_auto', models.BooleanField(default=True)),
                ('coordenacao', models.TextField(blank=True)),
                ('coordenacao_auto', models.BooleanField(default=True)),
                ('consideracoes', models.TextField(blank=True)),
                ('consideracoes_auto', models.BooleanField(default=True)),
                ('saida_em', models.DateTimeField(blank=True, null=True, verbose_name='saída da sede')),
                ('chegada_em', models.DateTimeField(blank=True, null=True, verbose_name='chegada na sede')),
                ('diarias_composicao', models.CharField(blank=True, max_length=120)),
                ('diarias_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diarias_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('atividades_texto', models.TextField(blank=True)),
                ('metas', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('unidade_movel_texto', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='assinante deste plano')),
                ('atividades', models.ManyToManyField(blank=True, related_name='planos', to='cadastros.atividadeplano')),
                ('coordenador_adm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='coordenador administrativo')),
                ('coordenador_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor', verbose_name='coordenador operacional')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficios', models.ManyToManyField(blank=True, related_name='planos', to='viagens.oficio')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='cadastros.programasolicitante', verbose_name='programa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='cadastros.unidade')),
            ],
            options={
                'verbose_name': 'plano de trabalho',
                'verbose_name_plural': 'planos de trabalho',
                'ordering': ['-ano', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EfetivoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.cargo')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.unidade')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efetivo', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.UniqueConstraint(fields=('ano', 'numero'), name='plano_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='plano_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', False)), _connector='OR'), name='plano_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelado', True), _negated=True), models.Q(('motivo_cancelamento', ''), _negated=True), _connector='OR'), name='plano_cancelado_tem_motivo'),
        ),
        migrations.AddConstraint(
            model_name='planotrabalho',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diarias_unitario__isnull', True), ('diarias_unitario__gte', 0), _connector='OR'), models.Q(('diarias_total__isnull', True), ('diarias_total__gte', 0), _connector='OR')), name='plano_diarias_nao_negativas'),
        ),
        migrations.AddConstraint(
            model_name='planodestino',
            constraint=models.UniqueConstraint(fields=('plano', 'municipio'), name='plano_destino_unico'),
        ),
        migrations.AddConstraint(
            model_name='efetivoplano',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='efetivo_quantidade_positiva'),
        ),
    ]
