# Generated by Django 6.1.1 on 2026-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0018_planos_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planotrabalho',
            name='coordenador_adm_genero',
            field=models.CharField(blank=True, choices=[('M', 'o Coordenador'), ('F', 'a Coordenadora')], max_length=1),
        ),
        migrations.AlterField(
            model_name='planotrabalho',
            name='coordenador_op_genero',
            field=models.CharField(blank=True, choices=[('M', 'o Coordenador'), ('F', 'a Coordenadora')], max_length=1),
        ),
    ]
