# Generated by Django 6.1.1 on 2026-10-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_coordenador_plano_genero'),
        ('viagens', '0019_plano_genero_sem_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
                ('programa_outros', models.CharField(blank=True, max_length=200, verbose_name='outro programa')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início do evento')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim do evento')),
                ('horario', models.CharField(blank=True, max_length=60, verbose_name='horário de atendimento')),
                ('coordenador_op_nome', models.CharField(blank=True, max_length=255)),
                ('coordenador_op_cargo', models.CharField(blank=True, max_length=120)),
                ('coordenador_op_genero', models.CharField(blank=True, max_length=1)),
                ('atividades_texto', models.TextField(blank=True)),
                ('metas', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('unidade_movel_texto', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividades', models.ManyToManyField(blank=True, related_name='+', to='cadastros.atividadeplano')),
                ('coordenador_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.servidor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='viagens.planotrabalho')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.programasolicitante')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.eventoplano')),
            ],
            options={
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventoplano',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), models.Q(('data_fim__gte', models.F('data_inicio')), ('data_inicio__isnull', False)), _connector='OR'), name='evento_plano_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='eventodestino',
            constraint=models.UniqueConstraint(fields=('evento', 'municipio'), name='evento_destino_unico'),
        ),
    ]
