# Generated by Django 6.1.1 on 2026-10-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_coordenador_plano_genero'),
        ('viagens', '0021_eventos_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=500, verbose_name='observação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.atividadeplano')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='viagens.planotrabalho')),
            ],
            options={
                'ordering': ['atividade__nome'],
                'constraints': [models.UniqueConstraint(fields=('plano', 'atividade'), name='resultado_atividade_unico')],
            },
        ),
    ]
