# Generated by Django 6.1.1 on 2026-10-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0023_resultados_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(choices=[('criado', 'Rascunho criado'), ('alterado', 'Dados alterados'), ('viajante', 'Equipe alterada'), ('emitido', 'Ofício emitido'), ('documento', 'Documento gerado'), ('reaberto', 'Reaberto para correção'), ('cancelado', 'Ofício cancelado'), ('reativado', 'Ofício reativado'), ('arquivado', 'Ofício arquivado'), ('desarquivado', 'Ofício desarquivado'), ('texto', 'Texto do documento alterado'), ('assinado', 'Via assinada')], max_length=12),
        ),
        migrations.CreateModel(
            name='ViaAssinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oficio', 'Ofício'), ('justificativa', 'Justificativa'), ('termo', 'Termo de autorização'), ('ordem', 'Ordem de serviço')], max_length=15)),
                ('chave', models.CharField(blank=True, max_length=20)),
                ('arquivo', models.FileField(upload_to='assinados/%Y/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('tamanho', models.PositiveIntegerField()),
                ('impressao_dos_dados', models.CharField(blank=True, max_length=64)),
                ('conferencia', models.JSONField(blank=True, default=dict, verbose_name='o que se leu do PDF')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('revogada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_revogacao', models.CharField(blank=True, max_length=300)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vias_assinadas', to='viagens.documento')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vias_assinadas', to='viagens.oficio')),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vias_assinadas', to='viagens.ordemservico')),
                ('revogada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vias_assinadas', to='viagens.termoautorizacao')),
            ],
            options={
                'verbose_name': 'via assinada',
                'verbose_name_plural': 'vias assinadas',
                'ordering': ['-enviado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('oficio__isnull', False), ('ordem__isnull', True), ('termo__isnull', True), ('tipo__in', ['oficio', 'justificativa'])), models.Q(('oficio__isnull', True), ('ordem__isnull', True), ('termo__isnull', False), ('tipo', 'termo')), models.Q(('oficio__isnull', True), ('ordem__isnull', False), ('termo__isnull', True), ('tipo', 'ordem')), _connector='OR'), name='via_assinada_um_dono_do_tipo'), models.CheckConstraint(condition=models.Q(('sha256', ''), _negated=True), name='via_assinada_tem_hash'), models.UniqueConstraint(condition=models.Q(('revogada_em__isnull', True)), fields=('tipo', 'oficio', 'termo', 'ordem', 'chave'), name='via_assinada_uma_vigente', nulls_distinct=False)],
            },
        ),
    ]
