# Generated by Django 6.1.1 on 2026-10-04 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_tipos_de_viagem'),
        ('viagens', '0025_vias_assinadas_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição/objetivo')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('preparacao', 'Em preparação'), ('gerados', 'Documentos gerados'), ('cancelada', 'Cancelada')], default='rascunho', max_length=12)),
                ('situacao_anterior', models.CharField(blank=True, choices=[('rascunho', 'Rascunho'), ('preparacao', 'Em preparação'), ('gerados', 'Documentos gerados'), ('cancelada', 'Cancelada')], max_length=12)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=1000, verbose_name='motivo do cancelamento')),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipos', models.ManyToManyField(blank=True, related_name='viagens', to='cadastros.tipoviagem')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='cadastros.unidade')),
            ],
            options={
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roteiros', to='viagens.viagem'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='viagens.viagem'),
        ),
        migrations.CreateModel(
            name='ViagemDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='viagens.viagem')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_inicio__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='viagem_periodo_ordenado'),
        ),
        migrations.AddConstraint(
            model_name='viagemdestino',
            constraint=models.UniqueConstraint(fields=('viagem', 'ordem'), name='viagem_destino_ordem_unica'),
        ),
    ]
