# Generated by Django 6.1.1 on 2026-10-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_tipos_de_viagem_auditoria'),
        ('viagens', '0027_viagem_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prestacao', to='viagens.oficio')),
            ],
            options={
                'verbose_name': 'prestação de contas',
                'verbose_name_plural': 'prestações de contas',
            },
        ),
        migrations.CreateModel(
            name='PrestacaoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitacao', models.CharField(blank=True, max_length=60, verbose_name='nº da solicitação')),
                ('data_liberacao_diarias', models.DateField(blank=True, null=True, verbose_name='liberação das diárias')),
                ('prazo_limite_saque', models.DateField(blank=True, null=True, verbose_name='prazo limite de saque')),
                ('diaria_valor_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diaria_valor_override_observacao', models.CharField(blank=True, max_length=255)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('preenchimento', 'Em preenchimento'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('devolvida', 'Devolvida')], default='pendente', max_length=14)),
                ('arquivada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('justificativa_finalizacao', models.TextField(blank=True)),
                ('enviada_em', models.DateField(blank=True, null=True)),
                ('protocolo_envio', models.CharField(blank=True, max_length=120, verbose_name='protocolo ou e-mail do envio')),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_devolucao', models.TextField(blank=True)),
                ('removida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='viagens.prestacaocontas')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacoes', to='cadastros.servidor')),
            ],
            options={
                'verbose_name': 'prestação de servidor',
                'verbose_name_plural': 'prestações de servidor',
                'ordering': ['servidor__nome'],
                'constraints': [models.UniqueConstraint(fields=('prestacao', 'servidor'), name='prestacao_servidor_unica'), models.CheckConstraint(condition=models.Q(('prazo_limite_saque__isnull', True), ('data_liberacao_diarias__isnull', True), ('prazo_limite_saque__gte', models.F('data_liberacao_diarias')), _connector='OR'), name='prestacao_prazo_depois_da_liberacao'), models.CheckConstraint(condition=models.Q(('diaria_valor_override__isnull', True), ('diaria_valor_override__gt', 0), _connector='OR'), name='prestacao_diaria_positiva')],
            },
        ),
    ]
