# Generated by Django 6.1.1 on 2026-10-05 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_tipos_de_viagem_auditoria'),
        ('viagens', '0029_prestacao_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_modo', models.CharField(choices=[('oficio', 'Manter o motorista do ofício'), ('servidor', 'Outro servidor deste ofício'), ('outro_oficio', 'Motorista de outro ofício')], default='oficio', max_length=12)),
                ('motorista_nome', models.CharField(blank=True, max_length=255, verbose_name='nome do motorista')),
                ('motorista_cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF do motorista')),
                ('motorista_oficio', models.CharField(blank=True, max_length=16, verbose_name='ofício do motorista')),
                ('motorista_protocolo', models.CharField(blank=True, max_length=30, verbose_name='protocolo do motorista')),
                ('viatura_modo', models.CharField(choices=[('oficio', 'Manter a viatura do ofício'), ('cadastro', 'Escolher do cadastro'), ('manual', 'Preencher à mão')], default='oficio', max_length=10)),
                ('viatura_modelo', models.CharField(blank=True, max_length=120, verbose_name='modelo')),
                ('viatura_placa', models.CharField(blank=True, max_length=8, verbose_name='placa')),
                ('viatura_tipo', models.CharField(blank=True, choices=[('caracterizada', 'Caracterizada'), ('descaracterizada', 'Descaracterizada')], max_length=20, verbose_name='tipo')),
                ('viatura_combustivel', models.CharField(blank=True, max_length=60, verbose_name='combustível')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista_servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.servidor')),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diario', to='viagens.prestacaocontas')),
                ('viatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.viatura')),
            ],
            options={
                'verbose_name': 'diário de bordo',
                'verbose_name_plural': 'diários de bordo',
            },
        ),
        migrations.CreateModel(
            name='DiarioBordoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='km inicial')),
                ('km_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='km final')),
                ('abastecimento', models.BooleanField(blank=True, default=True, null=True, verbose_name='necessidade de abastecimento')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='viagens.diariobordo')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens.trecho')),
            ],
            options={
                'verbose_name': 'trecho do diário de bordo',
                'verbose_name_plural': 'trechos do diário de bordo',
                'ordering': ['diario', 'ordem', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('diario', 'ordem'), name='diario_linha_ordem_unica'), models.CheckConstraint(condition=models.Q(('km_inicial__isnull', True), ('km_final__isnull', True), ('km_final__gte', models.F('km_inicial')), _connector='OR'), name='diario_km_final_depois_do_inicial', violation_error_message='O km final não pode ser menor que o km inicial.')],
            },
        ),
    ]
