# Generated by Django 6.1.1 on 2026-10-05 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0031_diario_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, verbose_name='descrição do evento')),
                ('diaria', models.CharField(blank=True, max_length=255, verbose_name='diária')),
                ('translado', models.CharField(blank=True, max_length=255, verbose_name='translado')),
                ('combustivel', models.CharField(blank=True, max_length=255, verbose_name='combustível')),
                ('passagem', models.CharField(blank=True, max_length=255, verbose_name='passagem')),
                ('atividade', models.TextField(blank=True, verbose_name='objetivo da participação')),
                ('conclusao', models.TextField(blank=True, verbose_name='conclusão')),
                ('medidas', models.TextField(blank=True, verbose_name='medidas a serem adotadas pelo órgão')),
                ('info_complementares', models.TextField(blank=True, verbose_name='informações complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='relatorio', to='viagens.prestacaocontas')),
            ],
            options={
                'verbose_name': 'relatório técnico',
                'verbose_name_plural': 'relatórios técnicos',
            },
        ),
    ]
