# Generated by Django 6.1.1 on 2026-10-05 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0033_relatorio_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('despacho', 'Despacho assinado do ofício'), ('comprovante', 'Comprovante de saque/transferência'), ('rt_assinado', 'Relatório técnico assinado'), ('db_assinado', 'Diário de bordo assinado')], max_length=15)),
                ('arquivo', models.FileField(upload_to='prestacao/%Y/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('tamanho', models.PositiveIntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da operação')),
                ('data_operacao', models.DateField(blank=True, null=True, verbose_name='data da operação')),
                ('operacao', models.CharField(blank=True, choices=[('saque', 'Saque'), ('transferencia', 'Transferência'), ('pix', 'Pix'), ('ted', 'TED'), ('doc', 'DOC'), ('deposito', 'Depósito')], max_length=15, verbose_name='operação')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('removido_motivo', models.CharField(blank=True, choices=[('excluido', 'Removido'), ('substituido', 'Substituído')], max_length=12)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='viagens.prestacaocontas')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos', to='viagens.prestacaoservidor')),
            ],
            options={
                'verbose_name': 'anexo da prestação',
                'verbose_name_plural': 'anexos da prestação',
                'ordering': ['tipo', 'enviado_em', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__isnull', True), ('valor__gt', 0), _connector='OR'), name='anexo_prestacao_valor_positivo'), models.CheckConstraint(condition=models.Q(('sha256', ''), _negated=True), name='anexo_prestacao_tem_hash'), models.CheckConstraint(condition=models.Q(models.Q(('servidor__isnull', False), ('tipo__in', ['comprovante', 'rt_assinado'])), models.Q(('servidor__isnull', True), ('tipo__in', ['despacho', 'db_assinado'])), _connector='OR'), name='anexo_prestacao_dono_do_tipo')],
            },
        ),
    ]
