# Generated by Django 6.1.1 on 2026-10-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_textos_do_rt'),
        ('viagens', '0035_anexos_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaocontas',
            name='diarias_realizadas_calculo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='diarias_realizadas_erro',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='diarias_realizadas_resumo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='prestacaocontas',
            name='diarias_realizadas_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TrechoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('saida_em', models.DateTimeField(verbose_name='saída')),
                ('chegada_em', models.DateTimeField(verbose_name='chegada')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distância (km)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio')),
                ('prestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos_realizados', to='viagens.prestacaocontas')),
                ('trecho_oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens.trecho')),
            ],
            options={
                'verbose_name': 'trecho realizado',
                'verbose_name_plural': 'trechos realizados',
                'ordering': ['prestacao', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='diariobordotrecho',
            name='realizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='viagens.trechorealizado'),
        ),
        migrations.AddConstraint(
            model_name='trechorealizado',
            constraint=models.UniqueConstraint(fields=('prestacao', 'ordem'), name='trecho_realizado_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='trechorealizado',
            constraint=models.CheckConstraint(condition=models.Q(('chegada_em__gt', models.F('saida_em'))), name='trecho_realizado_chega_depois'),
        ),
    ]
