# Generated by Django 6.1.1 on 2026-10-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0037_realizados_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarimboSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.PositiveSmallIntegerField(default=0, verbose_name='página')),
                ('x', models.FloatField(help_text='Fração da largura, 0 = borda esquerda.')),
                ('y', models.FloatField(help_text='Fração da altura, 0 = topo da página.')),
                ('tamanho', models.FloatField(default=0.012, help_text='Altura da letra, fração da página.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='viagens.prestacaoservidor')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='viagens.viaassinada')),
            ],
            options={
                'verbose_name': 'carimbo do número de solicitação',
                'verbose_name_plural': 'carimbos do número de solicitação',
                'ordering': ['pagina', 'y', 'x', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('via', 'servidor'), name='carimbo_unico_na_via'), models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1), ('y__gte', 0), ('y__lte', 1)), name='carimbo_dentro_da_pagina')],
            },
        ),
    ]
