# Generated by Django 6.1.1 on 2026-10-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0039_carimbo_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='transporte_meio',
            field=models.CharField(blank=True, choices=[('aereo', 'Aéreo'), ('ferroviario', 'Ferroviário'), ('maritimo', 'Marítimo'), ('onibus_linha', 'Rodoviário — ônibus de linha'), ('onibus_fretado', 'Rodoviário — ônibus fretado'), ('veiculo_fretado', 'Rodoviário — veículo fretado'), ('veiculo_oficial', 'Rodoviário — veículo oficial de outro órgão'), ('taxigov', 'TAXIGOV'), ('sem_custo', 'Sem custo para o Estado')], max_length=20, verbose_name='meio de transporte'),
        ),
    ]
