# Generated by Django 6.1.1 on 2026-10-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0040_meio_de_transporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('acao', models.CharField(choices=[('editado', 'Texto editado'), ('restaurado', 'Versão restaurada'), ('modelo', 'Voltou ao modelo')], default='editado', max_length=10)),
                ('regioes', models.JSONField(blank=True, default=dict, verbose_name='HTML por região')),
                ('blocos_alterados', models.JSONField(blank=True, default=list)),
                ('impressoes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='viagens.edicaotermo')),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes', to='viagens.termoautorizacao')),
            ],
            options={
                'verbose_name': 'edição de termo',
                'verbose_name_plural': 'edições de termo',
                'ordering': ['chave', '-numero'],
                'constraints': [models.UniqueConstraint(fields=('termo', 'chave', 'numero'), name='edicao_termo_numero_unico')],
            },
        ),
        auditar_tabela("viagens_edicaotermo"),
    ]
