# Generated by Django 6.1.1 on 2026-10-06 19:44

"""Efetivo, deslocamento e diárias passam a ser de cada evento do plano (o coordenador
operacional, que era do evento, volta a ser só do plano). Os eventos que já existem herdam
o efetivo e o deslocamento do plano (era a mesma equipe numa viagem só)."""

import django.db.models.deletion
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


def herdar_do_plano(apps, schema_editor):
    EventoPlano = apps.get_model("viagens", "EventoPlano")
    EfetivoEvento = apps.get_model("viagens", "EfetivoEvento")
    for evento in EventoPlano.objects.select_related("plano").iterator():
        plano = evento.plano
        evento.saida_em, evento.chegada_em = plano.saida_em, plano.chegada_em
        evento.diarias_composicao = plano.diarias_composicao
        evento.diarias_unitario, evento.diarias_total = plano.diarias_unitario, plano.diarias_total
        evento.save(
            update_fields=[
                "saida_em",
                "chegada_em",
                "diarias_composicao",
                "diarias_unitario",
                "diarias_total",
            ]
        )
        EfetivoEvento.objects.bulk_create(
            [
                EfetivoEvento(
                    evento=evento,
                    unidade_id=e.unidade_id,
                    cargo_id=e.cargo_id,
                    quantidade=e.quantidade,
                    posicao=e.posicao,
                )
                for e in plano.efetivo.order_by("posicao", "id")
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0016_textos_do_rt"),
        ("viagens", "0046_plano_programas"),
    ]

    operations = [
        migrations.CreateModel(
            name="EfetivoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantidade", models.PositiveSmallIntegerField(default=1)),
                ("posicao", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["posicao", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="eventoplano",
            name="coordenador_op",
        ),
        migrations.RemoveField(
            model_name="eventoplano",
            name="coordenador_op_cargo",
        ),
        migrations.RemoveField(
            model_name="eventoplano",
            name="coordenador_op_genero",
        ),
        migrations.RemoveField(
            model_name="eventoplano",
            name="coordenador_op_nome",
        ),
        migrations.AddField(
            model_name="eventoplano",
            name="chegada_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="chegada na sede"),
        ),
        migrations.AddField(
            model_name="eventoplano",
            name="diarias_composicao",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="eventoplano",
            name="diarias_total",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="eventoplano",
            name="diarias_unitario",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="eventoplano",
            name="saida_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="saída da sede"),
        ),
        migrations.AddConstraint(
            model_name="eventoplano",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("saida_em__isnull", True),
                    ("chegada_em__isnull", True),
                    ("chegada_em__gt", models.F("saida_em")),
                    _connector="OR",
                ),
                name="evento_plano_chegada_depois_da_saida",
            ),
        ),
        migrations.AddField(
            model_name="efetivoevento",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cadastros.cargo"
            ),
        ),
        migrations.AddField(
            model_name="efetivoevento",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="efetivo",
                to="viagens.eventoplano",
            ),
        ),
        migrations.AddField(
            model_name="efetivoevento",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cadastros.unidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="efetivoevento",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade__gte", 1)),
                name="efetivo_evento_quantidade_positiva",
            ),
        ),
        auditar_tabela("viagens_efetivoevento"),
        migrations.RunPython(herdar_do_plano, migrations.RunPython.noop),
    ]
