# Generated by Django 6.1.1 on 2026-10-05 18:01

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do pedido')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='horário do pedido')),
                ('jornalista', models.CharField(max_length=150, verbose_name='jornalista')),
                ('contato', models.CharField(blank=True, max_length=150, verbose_name='contato')),
                ('pedido', models.TextField(verbose_name='pedido')),
                ('situacao', models.CharField(choices=[('em_andamento', 'Em andamento'), ('em_andamento_texto', 'Em andamento — texto'), ('em_andamento_video', 'Em andamento — vídeo'), ('aguardando_fonte', 'Aguardando fonte'), ('aguardando_produtora', 'Aguardando produtora'), ('aguardar_nova_solicitacao', 'Aguardar nova solicitação'), ('proximo_mes', 'Próximo mês'), ('atendido', 'Atendido'), ('nao_responder', 'Não responder')], default='em_andamento', max_length=30, verbose_name='situação')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline / veiculação')),
                ('horario_resposta', models.TimeField(blank=True, null=True, verbose_name='horário da resposta')),
                ('fonte', models.TextField(blank=True, verbose_name='fontes consultadas')),
                ('inicio_pedido', models.TextField(blank=True, verbose_name='início do pedido às fontes')),
                ('final_pedido', models.TextField(blank=True, verbose_name='retorno das fontes')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta enviada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_imprensa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atendimento à imprensa',
                'verbose_name_plural': 'atendimentos à imprensa',
                'ordering': ['-data', '-horario', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(choices=[('em_andamento', 'Em andamento'), ('em_andamento_texto', 'Em andamento — texto'), ('em_andamento_video', 'Em andamento — vídeo'), ('aguardando_fonte', 'Aguardando fonte'), ('aguardando_produtora', 'Aguardando produtora'), ('aguardar_nova_solicitacao', 'Aguardar nova solicitação'), ('proximo_mes', 'Próximo mês'), ('atendido', 'Atendido'), ('nao_responder', 'Não responder')], max_length=30)),
                ('situacao_nova', models.CharField(choices=[('em_andamento', 'Em andamento'), ('em_andamento_texto', 'Em andamento — texto'), ('em_andamento_video', 'Em andamento — vídeo'), ('aguardando_fonte', 'Aguardando fonte'), ('aguardando_produtora', 'Aguardando produtora'), ('aguardar_nova_solicitacao', 'Aguardar nova solicitação'), ('proximo_mes', 'Próximo mês'), ('atendido', 'Atendido'), ('nao_responder', 'Não responder')], max_length=30)),
                ('anotacao', models.TextField(blank=True)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='imprensa.atendimento')),
            ],
            options={
                'verbose_name': 'andamento do atendimento',
                'verbose_name_plural': 'andamentos dos atendimentos',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'integrante da equipe',
                'verbose_name_plural': 'equipe de atendimento',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='imprensa_integrante_nome')],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='imprensa.integrante', verbose_name='responsável pelo atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='responsavel_resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='imprensa.integrante', verbose_name='responsável pela resposta'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'veículo de imprensa',
                'verbose_name_plural': 'veículos de imprensa',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='imprensa_veiculo_nome')],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='imprensa.veiculo', verbose_name='veículo'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['situacao', 'data'], name='imprensa_situacao_data'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['deadline'], name='imprensa_deadline'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__isnull', True), ('deadline__gte', models.F('data')), _connector='OR'), name='imprensa_deadline_depois_do_pedido'),
        ),
    ]
