# Generated by Django 6.1.1 on 2026-10-01 15:59

import django.db.models.functions.text
import django.utils.timezone
import gestao.identidade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativaAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=150)),
                ("ip", models.GenericIPAddressField(null=True)),
                (
                    "ocorrida_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["identificador", "ocorrida_em"],
                        name="identidade__identif_bacca3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "login",
                    models.CharField(max_length=60, unique=True, verbose_name="login"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail institucional"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="nome completo"),
                ),
                (
                    "unidade_sigla",
                    models.CharField(blank=True, max_length=40, verbose_name="unidade"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="acesso administrativo"
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("deve_trocar_senha", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuário",
                "verbose_name_plural": "usuários",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("login"),
                        name="usuario_login_ci_unico",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="usuario_email_ci_unico",
                    ),
                ],
            },
            managers=[
                ("objects", gestao.identidade.models.GerenciadorUsuarios()),
            ],
        ),
    ]
