# Generated by Django 6.1.1 on 2026-10-05 18:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'integrante da equipe',
                'verbose_name_plural': 'equipe de comunicação',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='publicacoes_integrante_nome')],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da pauta')),
                ('fonte', models.CharField(blank=True, max_length=200, verbose_name='fonte da pauta')),
                ('inicio_pauta', models.TimeField(blank=True, null=True, verbose_name='início da pauta')),
                ('titulo', models.CharField(max_length=300, verbose_name='título da pauta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('publicada', 'Publicada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='status')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('colocada_edicao', models.TimeField(blank=True, null=True, verbose_name='colocada para edição')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('horario_publicacao', models.TimeField(blank=True, null=True, verbose_name='horário de publicação')),
                ('bitly_grupos', models.BooleanField(blank=True, null=True, verbose_name='Bitly nos grupos')),
                ('enviado_sesp', models.BooleanField(blank=True, null=True, verbose_name='enviado para a SESP')),
                ('publicado_aen', models.BooleanField(blank=True, null=True, verbose_name='publicado na AEN')),
                ('link_site', models.URLField(blank=True, max_length=500, verbose_name='link no site da PCPR')),
                ('link_aen', models.URLField(blank=True, max_length=500, verbose_name='link na AEN')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes', to=settings.AUTH_USER_MODEL)),
                ('galeria_fotos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='galerias', to='publicacoes.integrante', verbose_name='galeria de fotos')),
                ('jornalista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pautas', to='publicacoes.integrante', verbose_name='jornalista responsável')),
                ('revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='publicacoes.integrante', verbose_name='revisão')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-data', '-inicio_pauta', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('publicada', 'Publicada'), ('cancelada', 'Cancelada')], max_length=15)),
                ('status_novo', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('publicada', 'Publicada'), ('cancelada', 'Cancelada')], max_length=15)),
                ('anotacao', models.TextField(blank=True)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='publicacoes.publicacao')),
            ],
            options={
                'verbose_name': 'andamento da pauta',
                'verbose_name_plural': 'andamentos das pautas',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'unidade responsável',
                'verbose_name_plural': 'unidades responsáveis',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='publicacoes_unidade_nome')],
            },
        ),
        migrations.AddField(
            model_name='publicacao',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pautas', to='publicacoes.unidaderesponsavel', verbose_name='unidade responsável'),
        ),
        migrations.AddIndex(
            model_name='publicacao',
            index=models.Index(fields=['status', 'data'], name='publicacoes_status_data'),
        ),
        migrations.AddIndex(
            model_name='publicacao',
            index=models.Index(fields=['data_publicacao'], name='publicacoes_data_pub'),
        ),
        migrations.AddConstraint(
            model_name='publicacao',
            constraint=models.CheckConstraint(condition=models.Q(('data_publicacao__isnull', True), ('data_publicacao__gte', models.F('data')), _connector='OR'), name='publicacoes_publicada_apos_pauta'),
        ),
    ]
