# Generated by Django 6.1.1 on 2026-10-05 21:59

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipe',
                'verbose_name_plural': 'equipes',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_equipe_nome')],
            },
        ),
        migrations.CreateModel(
            name='OrgaoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'órgão responsável',
                'verbose_name_plural': 'órgãos responsáveis',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_orgao_nome')],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_servico_nome')],
            },
        ),
        migrations.CreateModel(
            name='TextoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(verbose_name='texto')),
            ],
            options={
                'verbose_name': 'texto pronto do despacho',
                'verbose_name_plural': 'textos prontos do despacho',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_texto_nome')],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitante_padrao', models.CharField(blank=True, max_length=150, verbose_name='solicitante padrão')),
                ('cargo_padrao', models.CharField(blank=True, max_length=255, verbose_name='cargo / unidade padrão')),
                ('orgao_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eventos.orgaoresponsavel', verbose_name='órgão padrão')),
                ('servicos_sugeridos', models.ManyToManyField(blank=True, related_name='+', to='eventos.servico', verbose_name='serviços sugeridos')),
            ],
            options={
                'verbose_name': 'tipo de evento',
                'verbose_name_plural': 'tipos de evento',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEventoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de servidores')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eventos.equipe')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_padrao', to='eventos.tipoevento')),
            ],
            options={
                'verbose_name': 'equipe do modelo',
                'verbose_name_plural': 'equipes do modelo',
                'ordering': ['equipe__nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'unidade móvel',
                'verbose_name_plural': 'unidades móveis',
                'ordering': ['nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_unidade_movel_nome')],
            },
        ),
        migrations.AddConstraint(
            model_name='tipoevento',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='eventos_tipo_nome'),
        ),
        migrations.AddConstraint(
            model_name='tipoeventoequipe',
            constraint=models.UniqueConstraint(fields=('tipo_evento', 'equipe'), name='eventos_tipo_equipe_unica'),
        ),
    ]
