# Generated by Django 6.1.1 on 2026-10-05 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_textos_do_rt'),
        ('eventos', '0003_carga_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(verbose_name='data da solicitação')),
                ('data_inicio_evento', models.DateField(blank=True, null=True, verbose_name='início do evento')),
                ('data_fim_evento', models.DateField(blank=True, null=True, verbose_name='fim do evento')),
                ('solicitante_nome', models.CharField(blank=True, max_length=150, verbose_name='solicitante')),
                ('solicitante_cargo_unidade', models.CharField(blank=True, max_length=255, verbose_name='cargo / unidade')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('unidade_movel', models.BooleanField(default=False, verbose_name='unidade móvel')),
                ('local_evento', models.CharField(blank=True, max_length=255, verbose_name='local do evento')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('protocolo', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='protocolo')),
                ('descricao_complementar', models.TextField(blank=True, verbose_name='descrição complementar')),
                ('quantidade_servidores', models.PositiveIntegerField(default=0, verbose_name='total de servidores')),
                ('tipo_operacao', models.CharField(choices=[('diaria', 'Diária'), ('extrajornada', 'Extrajornada')], default='diaria', max_length=15, verbose_name='tipo de operação')),
                ('quantidade_cin', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de CIN agendadas')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_despacho', 'Aguardando despacho'), ('devolvida', 'Devolvida para correção'), ('deferida', 'Deferida — em andamento'), ('atendida', 'Atendida'), ('nao_atendida', 'Não atendida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=25, verbose_name='status')),
                ('decisao_dg', models.CharField(choices=[('pendente', 'Pendente'), ('atender', 'Atender'), ('nao_atender', 'Não atender'), ('cancelado', 'Evento cancelado')], default='pendente', max_length=15, verbose_name='decisão da DG')),
                ('observacoes_dg', models.TextField(blank=True, verbose_name='observações da DG')),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_evento', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_evento', to='cadastros.servidor', verbose_name='motorista')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_evento', to='cadastros.municipio', verbose_name='município')),
                ('orgao_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='eventos.orgaoresponsavel', verbose_name='órgão responsável')),
                ('tipo_evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='eventos.tipoevento', verbose_name='tipo de evento')),
                ('unidade_movel_designada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='eventos.unidademovel', verbose_name='qual unidade móvel')),
            ],
            options={
                'verbose_name': 'solicitação de evento',
                'verbose_name_plural': 'solicitações de evento',
                'ordering': ['-data_solicitacao', '-criado_em'],
                'permissions': [('despachar_solicitacao', 'Despachar solicitações de evento (DG)'), ('ver_todas_solicitacoes', 'Ver as solicitações de todos')],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Rascunho criado'), ('envio', 'Solicitação enviada'), ('devolucao', 'Enviada para correção'), ('reenvio', 'Alterada e reenviada para a DG'), ('ajuste_dg', 'Servidores ajustados pela DG'), ('decisao', 'Decisão da DG registrada'), ('conclusao', 'Atendimento confirmado'), ('cancelamento', 'Evento cancelado'), ('transferencia', 'Responsável transferido'), ('anexo', 'Anexos')], max_length=20)),
                ('status_anterior', models.CharField(blank=True, max_length=25)),
                ('status_novo', models.CharField(blank=True, max_length=25)),
                ('observacao', models.TextField(blank=True)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='eventos.solicitacao')),
            ],
            options={
                'verbose_name': 'movimento da solicitação',
                'verbose_name_plural': 'movimentos das solicitações',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='eventos/%Y/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='eventos.solicitacao')),
            ],
            options={
                'verbose_name': 'anexo da solicitação',
                'verbose_name_plural': 'anexos das solicitações',
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_servidores', models.PositiveIntegerField(blank=True, null=True, verbose_name='servidores')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='eventos.equipe')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='eventos.solicitacao')),
            ],
            options={
                'ordering': ['equipe__nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='eventos.servico')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='eventos.solicitacao')),
            ],
            options={
                'ordering': ['servico__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['status', 'data_inicio_evento'], name='eventos_solic_status_inicio'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_evento__isnull', True), ('data_fim_evento__isnull', True), ('data_fim_evento__gte', models.F('data_inicio_evento')), _connector='OR'), name='eventos_solic_periodo_valido'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoequipe',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'equipe'), name='eventos_solic_equipe_unica'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoservico',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'servico'), name='eventos_solic_servico_unico'),
        ),
    ]
