# Generated by Django 6.1.1 on 2026-10-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auditoria_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmar_atendimento', 'Confirmar o atendimento'), ('despacho_proximo', 'Despacho com evento próximo'), ('devolucao_parada', 'Devolução parada')], max_length=25)),
                ('referencia', models.DateField(verbose_name='data de referência')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='eventos.solicitacao')),
            ],
            options={
                'verbose_name': 'lembrete da solicitação',
                'verbose_name_plural': 'lembretes das solicitações',
                'ordering': ['-enviado_em'],
                'constraints': [models.UniqueConstraint(fields=('solicitacao', 'tipo', 'referencia'), name='eventos_lembrete_unico')],
            },
        ),
    ]
