# Generated by Django 6.1.1 on 2026-10-06 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from gestao.plataforma.auditoria import auditar_tabela


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_lembrete'),
        ('viagens', '0039_carimbo_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Rascunho criado'), ('envio', 'Solicitação enviada'), ('devolucao', 'Enviada para correção'), ('reenvio', 'Alterada e reenviada para a DG'), ('ajuste_dg', 'Servidores ajustados pela DG'), ('decisao', 'Decisão da DG registrada'), ('conclusao', 'Atendimento confirmado'), ('cancelamento', 'Evento cancelado'), ('transferencia', 'Responsável transferido'), ('anexo', 'Anexos'), ('viagem', 'Viagem gerada')], max_length=20),
        ),
        migrations.CreateModel(
            name='ViagemGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_geradas', to='eventos.solicitacao')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_de_evento', to='viagens.viagem')),
            ],
            options={
                'verbose_name': 'viagem gerada da solicitação',
                'verbose_name_plural': 'viagens geradas das solicitações',
                'ordering': ['criada_em', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('solicitacao', 'viagem'), name='eventos_viagem_gerada_unica')],
            },
        ),
        auditar_tabela("eventos_viagemgerada"),
    ]
