# Generated by Django 6.1.1 on 2026-10-05 19:25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0016_textos_do_rt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField(verbose_name='data da solicitação')),
                ('canal_solicitacao', models.CharField(blank=True, choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('protocolo', 'Protocolo'), ('telefone', 'Telefone'), ('presencial', 'Presencial'), ('outro', 'Outro')], max_length=20, verbose_name='foi solicitado via')),
                ('protocolo', models.CharField(blank=True, max_length=20, verbose_name='nº do protocolo')),
                ('solicitante', models.CharField(max_length=300, verbose_name='solicitante')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('assunto_email', models.CharField(blank=True, max_length=300, verbose_name='assunto do e-mail')),
                ('pedido_contato', models.TextField(blank=True, verbose_name='pedido/contato')),
                ('informacoes_previas', models.TextField(blank=True, verbose_name='informações prévias')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('evento', models.CharField(choices=[('palestra', 'Palestra'), ('pcpr_na_comunidade', 'PCPR na Comunidade'), ('evento', 'Evento')], default='palestra', max_length=25, verbose_name='evento')),
                ('data_inicio_evento', models.DateField(blank=True, null=True, verbose_name='data do evento')),
                ('data_fim_evento', models.DateField(blank=True, null=True, verbose_name='fim do evento')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('periodo_evento_texto', models.CharField(blank=True, max_length=200, verbose_name='observação do período')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='local do evento')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('quantidade_publico', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de público')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_retorno', 'Aguardando retorno'), ('agendada', 'Agendada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendente', max_length=25, verbose_name='status')),
                ('andamento', models.TextField(blank=True, verbose_name='andamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palestras', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='palestras', to='cadastros.municipio', verbose_name='município')),
            ],
            options={
                'verbose_name': 'palestra ou evento',
                'verbose_name_plural': 'palestras e eventos',
                'ordering': ['-data_solicitacao', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_retorno', 'Aguardando retorno'), ('agendada', 'Agendada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], max_length=25)),
                ('status_novo', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('aguardando_retorno', 'Aguardando retorno'), ('agendada', 'Agendada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], max_length=25)),
                ('anotacao', models.TextField(blank=True)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='palestras.palestra')),
            ],
            options={
                'verbose_name': 'andamento da palestra',
                'verbose_name_plural': 'andamentos das palestras',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('divisao', models.CharField(blank=True, max_length=100, verbose_name='divisão')),
                ('lotacao', models.CharField(blank=True, max_length=150, verbose_name='lotação')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('tema_abordagem', models.CharField(blank=True, max_length=300, verbose_name='tema de abordagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='palestrantes', to='cadastros.municipio', verbose_name='município')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palestrantes', to='cadastros.servidor', verbose_name='servidor no cadastro')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='palestra',
            name='palestrantes',
            field=models.ManyToManyField(blank=True, related_name='palestras', to='palestras.palestrante', verbose_name='palestrantes'),
        ),
        migrations.CreateModel(
            name='RespostaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='palestras.palestra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resposta enviada',
                'verbose_name_plural': 'respostas enviadas',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RespostaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, verbose_name='tipo')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'resposta padrão',
                'verbose_name_plural': 'respostas padrão',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('tipo'), name='palestras_resposta_tipo')],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='palestras_tema_nome')],
            },
        ),
        migrations.AddField(
            model_name='palestra',
            name='temas',
            field=models.ManyToManyField(blank=True, related_name='palestras', to='palestras.tema', verbose_name='temas'),
        ),
        migrations.AddConstraint(
            model_name='palestrante',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), django.db.models.functions.text.Lower('lotacao'), name='palestras_palestrante_nome_lotacao'),
        ),
        migrations.AddIndex(
            model_name='palestra',
            index=models.Index(fields=['status', 'data_solicitacao'], name='palestras_status_data'),
        ),
        migrations.AddIndex(
            model_name='palestra',
            index=models.Index(fields=['data_inicio_evento'], name='palestras_data_evento'),
        ),
        migrations.AddConstraint(
            model_name='palestra',
            constraint=models.CheckConstraint(condition=models.Q(('data_inicio_evento__isnull', True), ('data_fim_evento__isnull', True), ('data_fim_evento__gte', models.F('data_inicio_evento')), _connector='OR'), name='palestras_periodo_valido'),
        ),
    ]
