# Generated by Django 6.1.1 on 2026-10-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_viagem_gerada'),
        ('palestras', '0002_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='solicitacao_dg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palestras', to='eventos.solicitacao', verbose_name='solicitação à DG'),
        ),
    ]
