# Generated by Django 6.1.1 on 2026-10-06 01:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0016_textos_do_rt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vocativo', models.CharField(blank=True, default='Senhor(a) Diretor(a),', max_length=150, verbose_name='vocativo do ofício')),
                ('assinante', models.CharField(blank=True, max_length=150, verbose_name='quem assina o ofício')),
                ('cargo_assinante', models.CharField(blank=True, max_length=150, verbose_name='cargo de quem assina')),
                ('destinatario', models.TextField(blank=True, verbose_name='destinatário (uma linha por linha)')),
                ('assunto_protocolo', models.CharField(blank=True, default='LICITACAO', max_length=120, verbose_name='assunto do protocolo')),
                ('palavras_chave', models.CharField(blank=True, default='REGISTRO DE PRECO', max_length=200, verbose_name='palavras-chave do protocolo')),
                ('destino_despacho', models.CharField(blank=True, default='Ao GAF,', max_length=120, verbose_name='destino do despacho')),
                ('emails_ascom', models.CharField(blank=True, help_text='Vários separados por vírgula.', max_length=500, verbose_name='e-mail da ASCOM em cópia')),
                ('assunto_email_os', models.CharField(blank=True, default='Ordem de Serviço {numero} — {evento}', max_length=200, verbose_name='assunto do e-mail da ordem de serviço')),
                ('texto_email_os', models.TextField(blank=True, default='Prezados,\n\nSegue a Ordem de Serviço {numero} para o evento {evento}, em {data} às {horario}, em {local}, para {quantidade} pessoas. Responsável pelo recebimento: {responsavel}.\n\nAtenciosamente,\nASCOM/PCPR', verbose_name='texto do e-mail da ordem de serviço')),
                ('assunto_email_ob', models.CharField(blank=True, default='Ordem bancária — Ordem de Serviço {numero}', max_length=200, verbose_name='assunto do e-mail da ordem bancária')),
                ('texto_email_ob', models.TextField(blank=True, default='Prezados,\n\nInformamos o pagamento da nota fiscal {nota} referente à Ordem de Serviço {numero} ({evento}), pela ordem bancária {ordem_bancaria} de {data_ordem_bancaria}. Segue o comprovante.\n\nAtenciosamente,\nASCOM/PCPR', verbose_name='texto do e-mail da ordem bancária')),
            ],
            options={
                'verbose_name': 'configuração do ofício',
                'verbose_name_plural': 'configuração do ofício',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_curto', models.CharField(blank=True, help_text='Vai no detalhamento do protocolo. Em branco, usa a razão social sem LTDA/EIRELI/ME/EPP/S.A.', max_length=60, verbose_name='nome curto')),
                ('cnpj', models.CharField(blank=True, max_length=14, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=150, verbose_name='contato')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, help_text='Para onde vão a ordem de serviço e a ordem bancária.', max_length=254, verbose_name='e-mail')),
                ('portal_certidao_municipal', models.URLField(blank=True, help_text='Endereço da prefeitura da sede onde se emite a certidão municipal.', max_length=300, verbose_name='portal da certidão municipal')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['razao_social'],
                'permissions': [('acessar_coffee', 'Acessar o Coffee Break')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('razao_social'), name='coffee_fornecedor_razao_unica'), models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='coffee_fornecedor_cnpj_unico')],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, verbose_name='número')),
                ('numero_gms', models.CharField(blank=True, max_length=30, verbose_name='número GMS')),
                ('termo_aditivo', models.CharField(blank=True, help_text='Número que os documentos citam. Os termos aditivos ficam na aba própria.', max_length=30, verbose_name='termo aditivo em vigor')),
                ('fiscal', models.CharField(blank=True, max_length=150, verbose_name='fiscal do contrato')),
                ('cargo_fiscal', models.CharField(blank=True, default='Agente de Polícia Judiciária', max_length=120, verbose_name='cargo do fiscal')),
                ('clausula_pagamento', models.CharField(blank=True, default='Cláusula Décima, item 10.2.6', max_length=120, verbose_name='cláusula do pagamento')),
                ('arquivo', models.FileField(blank=True, upload_to='coffee/contratos/%Y/', verbose_name='PDF do contrato')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('vigencia_estimada', models.BooleanField(default=False, help_text='Marque quando o fim foi calculado pelo prazo (o termo aditivo confirma).', verbose_name='vigência estimada')),
                ('quantidade_contratada', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade contratada')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor total')),
                ('antecedencia_minima_dias', models.PositiveSmallIntegerField(default=2, verbose_name='antecedência mínima do pedido (dias)')),
                ('objeto', models.TextField(blank=True, verbose_name='objeto')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='coffee.fornecedor')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-vigencia_fim', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='número')),
                ('exercicio', models.CharField(help_text='Ex.: 2026.', max_length=9, verbose_name='exercício')),
                ('quantidade_total', models.PositiveIntegerField(verbose_name='quantidade total (unidades)')),
                ('empenho', models.CharField(blank=True, max_length=60, verbose_name='empenho')),
                ('valor_empenho', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor do empenho')),
                ('municipios_texto', models.TextField(blank=True, verbose_name='municípios (texto original)')),
                ('orientacoes', models.TextField(blank=True, verbose_name='orientações')),
                ('especificacoes', models.TextField(blank=True, verbose_name='especificações técnicas')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('ativo', models.BooleanField(default=True, help_text='Só lotes vigentes recebem pedidos pelo município.', verbose_name='lote vigente')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='coffee.contrato')),
                ('municipios', models.ManyToManyField(blank=True, related_name='+', to='cadastros.municipio', verbose_name='municípios abrangidos')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['-exercicio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='TermoAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, verbose_name='número')),
                ('arquivo', models.FileField(blank=True, upload_to='coffee/aditivos/%Y/', verbose_name='PDF do termo aditivo')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='início da vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='fim da vigência')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='coffee.contrato')),
            ],
            options={
                'verbose_name': 'termo aditivo',
                'verbose_name_plural': 'termos aditivos',
                'ordering': ['contrato__numero', 'vigencia_fim', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(fields=('numero',), name='coffee_contrato_numero'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_inicio__isnull', True), ('vigencia_fim__isnull', True), ('vigencia_fim__gte', models.F('vigencia_inicio')), _connector='OR'), name='coffee_contrato_vigencia_valida'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero', 'exercicio'), name='coffee_lote_unico'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_total__gte', 1)), name='coffee_lote_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='termoaditivo',
            constraint=models.UniqueConstraint(fields=('contrato', 'numero'), name='coffee_aditivo_numero_por_contrato'),
        ),
    ]
