# Generated by Django 6.1.1 on 2026-10-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_textos_do_rt'),
        ('coffee', '0002_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_solicitacao', models.DateField(verbose_name='data da solicitação')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Nº da OS')),
                ('descricao', models.TextField(verbose_name='descrição do evento (objeto da OS)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade de pessoas')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='data do evento')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('local_entrega', models.CharField(blank=True, max_length=255, verbose_name='local de entrega')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('responsavel', models.CharField(blank=True, help_text='Nome e telefone de quem recebe no local.', max_length=200, verbose_name='responsável pelo recebimento')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor unitário')),
                ('nota_fiscal', models.CharField(blank=True, max_length=60, verbose_name='nº da nota fiscal')),
                ('quantidade_faturada', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade faturada')),
                ('protocolo_pagamento', models.CharField(blank=True, max_length=20, verbose_name='protocolo de pagamento')),
                ('atesto_em', models.DateField(blank=True, null=True, verbose_name='atesto e envio ao GAF')),
                ('ordem_bancaria_em', models.DateField(blank=True, null=True, verbose_name='ordem bancária emitida em')),
                ('envio_empresa_em', models.DateField(blank=True, null=True, verbose_name='ordem bancária enviada à empresa em')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cancelada', models.BooleanField(default=False, verbose_name='cancelada')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, verbose_name='motivo do cancelamento')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='coffee.lote')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.municipio', verbose_name='município do evento')),
            ],
            options={
                'verbose_name': 'solicitação de coffee break',
                'verbose_name_plural': 'solicitações de coffee break',
                'ordering': ['-data_solicitacao', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criada', 'Solicitação criada'), ('atualizada', 'Solicitação atualizada'), ('cancelada', 'Solicitação cancelada'), ('reativada', 'Solicitação reativada')], max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='coffee.solicitacao')),
            ],
            options={
                'verbose_name': 'movimento da solicitação de coffee break',
                'verbose_name_plural': 'movimentos das solicitações de coffee break',
                'ordering': ['-em', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['lote', 'cancelada'], name='coffee_os_lote_ativa'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('numero',), name='coffee_os_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('cancelada', True), ('quantidade__gte', 1), _connector='OR'), name='coffee_os_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('ordem_bancaria_em__isnull', True), ('atesto_em__isnull', True), ('ordem_bancaria_em__gte', models.F('atesto_em')), _connector='OR'), name='coffee_os_ob_depois_do_atesto'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('envio_empresa_em__isnull', True), ('ordem_bancaria_em__isnull', True), ('envio_empresa_em__gte', models.F('ordem_bancaria_em')), _connector='OR'), name='coffee_os_envio_depois_da_ob'),
        ),
    ]
