# Generated by Django 6.1.1 on 2026-10-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auditoria_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_oficio',
            field=models.DateField(blank=True, null=True, verbose_name='data do ofício'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='em_correcao',
            field=models.BooleanField(default=False, verbose_name='aberta para correção'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='numero_oficio',
            field=models.CharField(blank=True, max_length=20, verbose_name='nº do ofício'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='protocolo_pcpr',
            field=models.CharField(blank=True, max_length=30, verbose_name='PCPR protocolo n.º'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='acao',
            field=models.CharField(choices=[('criada', 'Solicitação criada'), ('atualizada', 'Solicitação atualizada'), ('cancelada', 'Solicitação cancelada'), ('reativada', 'Solicitação reativada'), ('andamento', 'Andamento registrado'), ('correcao', 'Correção')], max_length=20),
        ),
    ]
