# Generated by Django 6.1.1 on 2026-10-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_fluxo_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='pagamento_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjuntas', to='coffee.solicitacao', verbose_name='pagamento junto com'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='acao',
            field=models.CharField(choices=[('criada', 'Solicitação criada'), ('atualizada', 'Solicitação atualizada'), ('cancelada', 'Solicitação cancelada'), ('reativada', 'Solicitação reativada'), ('andamento', 'Andamento registrado'), ('conjunto', 'Pagamento conjunto'), ('correcao', 'Correção')], max_length=20),
        ),
    ]
