# Generated by Django 6.1.1 on 2026-10-06 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_pagamento_conjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='acao',
            field=models.CharField(choices=[('criada', 'Solicitação criada'), ('atualizada', 'Solicitação atualizada'), ('cancelada', 'Solicitação cancelada'), ('reativada', 'Solicitação reativada'), ('andamento', 'Andamento registrado'), ('conjunto', 'Pagamento conjunto'), ('documento', 'Documento'), ('correcao', 'Correção')], max_length=20),
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=12)),
                ('arquivo', models.FileField(upload_to='coffee/vias/%Y/')),
                ('nome', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('assinada', models.BooleanField(default=False)),
                ('emitida_em', models.DateTimeField(auto_now_add=True)),
                ('removida_em', models.DateTimeField(blank=True, null=True)),
                ('emitida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vias', to='coffee.solicitacao')),
            ],
            options={
                'verbose_name': 'via de documento do coffee break',
                'verbose_name_plural': 'vias de documentos do coffee break',
                'ordering': ['-emitida_em', '-pk'],
                'indexes': [models.Index(fields=['solicitacao', 'tipo'], name='coffee_via_documento')],
            },
        ),
    ]
