# Generated by Django 6.1.1 on 2026-10-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0008_auditoria_vias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certidao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('federal', 'Federal'), ('estadual', 'Estadual (Paraná)'), ('municipal', 'Municipal'), ('trabalhista', 'Trabalhista'), ('fgts', 'FGTS')], max_length=12)),
                ('arquivo', models.FileField(upload_to='coffee/certidoes/%Y/')),
                ('validade', models.DateField(verbose_name='válida até')),
                ('aviso', models.CharField(blank=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('enviada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certidoes', to='coffee.fornecedor')),
            ],
            options={
                'verbose_name': 'certidão do fornecedor',
                'verbose_name_plural': 'certidões dos fornecedores',
                'ordering': ['tipo', '-validade', '-criada_em'],
            },
        ),
    ]
