# Generated by Django 6.1.1 on 2026-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0010_auditoria_certidoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='nota_cnpj',
            field=models.CharField(blank=True, max_length=14, verbose_name='CNPJ do emitente (lido)'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nota_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='emissão da nota (lida)'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nota_pdf',
            field=models.FileField(blank=True, upload_to='coffee/notas/%Y/', verbose_name='PDF da nota fiscal'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nota_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor da nota (lido)'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='ob_numero',
            field=models.CharField(blank=True, max_length=30, verbose_name='nº da ordem bancária (lido)'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='ob_pdf',
            field=models.FileField(blank=True, upload_to='coffee/ob/%Y/', verbose_name='PDF da ordem bancária'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='ob_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor da ordem bancária (lido)'),
        ),
    ]
