# Generated by Django 6.1.1 on 2026-10-06 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_pdfs_nota_ob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='acao',
            field=models.CharField(choices=[('criada', 'Solicitação criada'), ('atualizada', 'Solicitação atualizada'), ('cancelada', 'Solicitação cancelada'), ('reativada', 'Solicitação reativada'), ('andamento', 'Andamento registrado'), ('conjunto', 'Pagamento conjunto'), ('documento', 'Documento'), ('correcao', 'Correção'), ('entrega', 'Entrega registrada')], max_length=20),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sem_ocorrencia', 'Entregue sem ocorrência'), ('atraso', 'Atraso na entrega'), ('falta_itens', 'Falta de itens'), ('qualidade', 'Problema de qualidade'), ('nao_entregue', 'Não entregue'), ('outra', 'Outra ocorrência')], default='sem_ocorrencia', max_length=20, verbose_name='o que aconteceu')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='avaliação')),
                ('recebido_por', models.CharField(blank=True, max_length=150, verbose_name='quem recebeu')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('anexo', models.FileField(blank=True, upload_to='coffee/entregas/%Y/', verbose_name='foto ou documento')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='coffee.solicitacao')),
            ],
            options={
                'verbose_name': 'entrega do coffee break',
                'verbose_name_plural': 'entregas do coffee break',
                'ordering': ['-registrado_em', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('avaliacao__isnull', True), models.Q(('avaliacao__gte', 1), ('avaliacao__lte', 5)), _connector='OR'), name='coffee_entrega_avaliacao_1_a_5')],
            },
        ),
    ]
