# Generated by Django 6.1.1 on 2026-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_auditoria_entregas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='origem_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id na origem'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='origem_tipo',
            field=models.CharField(blank=True, max_length=20, verbose_name='origem do pedido'),
        ),
    ]
