# Generated by Django 6.1.1 on 2026-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0014_origem_do_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='email_impressao',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
